#pragma once
void fileOpen();
void fileClose();
void loadCursorPos();
void saveCursorPos();
void loadWindowSettings();
void saveWindowSettings();
void loadPlayCount();
void savePlayCount();
void loadRecordConfig();
