// stageData.cpp
#include "stageData.h"

std::vector<StageInfo> stageData = {
	// stageId, description, stageTitle, stageDescription, bgmFileName, patternFunc
	{ "sample", "AIに渡すためのサンプル。使える素材の一覧を教える", "", "", "field", EnemyPat_SampleForAI },
	{ "handmade1", "3WAY自機狙い", "", "", "Torpedo_Hymn2", EnemyPat_3Way },
	{ "handmade2", "全方位", "", "", "Torpedo_Hymn2", EnemyPat_Round },
	{ "handmade3", "破裂弾", "", "", "Torpedo_Hymn2", EnemyPat_Burst },
	{ "handmade4", "波と粒の境界（目コピ）", "", "", "Torpedo_Hymn2", EnemyPat_Namitsubu },
	{ "handmade5", "ドーブルをモチーフにした弾幕。くろいまなざし→キノコのほうし→ロックオン→つのドリル", "画符「スケッチ・オブ・デス」", "", "Torpedo_Hymn2", EnemyPat_Smeargle },
	{ "handmade6", "世界のナベアツをモチーフにした弾幕", "数符「デジタル・アホリズム」", "", "Flying Futon Frenzy 2", EnemyPat_Nabeatsu },
	{ "handmade7", "トルコ行進曲を演奏する弾幕", "鍵符「七彩のレーザーキーボード」", "", "Turkish March", EnemyPat_TurkishMarch },
	{ "handmade8", "サーカス・ギャロップを演奏する弾幕", "奏符「フォーリング・スケール」", "", "Circus Galop", EnemyPat_CircusGalop },
	{ "handmade9", "オセロの棋譜並べをする弾幕", "盤符「リバーシブル・リバース」", "", "Moonlit Danmaku Run", EnemyPat_Othello },
	{ "handmade10", "自機と戦える弾幕", "鏡像「ファントム・スラスター」", "自機の姿を精密に模したドット絵風の弾幕を生成し、自機に向けて突撃させます。機体後部から噴射弾幕を常時撒き散らしながら迫り来る、ドッペルゲンガーのような迫力と虚像感を兼ね備えた弾幕パターンです。", "Locrian Barrage", EnemyPat_PlayerIMG },
	{ "handmade11", "おっぱい弾幕", "乳符「揺蕩う双丘と甘き雫」", "敵は時間と共に緩やかに形を変える豊満な曲線を弾で描き出し、その頂から重力に引かれる雫のような弾を間歇的に噴出させる。曲線は左右対称に反転して現れ、空間を柔らかく埋め尽くしていく。", "Tidal Ascend", EnemyPat_Oppai },
	{ "ClaudeEX1", "高難易度の弾幕", "", "", "Torpedo_Hymn", EnemyPat_Difficulty_Claude },
	{ "ClaudeEX2", "幾何学的に美しい弾幕 アナザー", "", "", "Torpedo_Hymn", EnemyPat_Geometry_Claude2 },
	{ "GrokEX1", "彗星をモチーフにした弾幕 アナザー", "", "", "Torpedo_Hymn", EnemyPat_Comet_Grok2 },
	{ "GeminiEx1", "達人王みたいな弾幕", "", "", "Torpedo_Hymn", EnemyPat_Tatsujinou_Gemini },
	{ "DeepSeekEx2", "はっぱカッターをモチーフにした弾幕 アナザー", "", "", "Torpedo_Hymn", EnemyPat_RazorLeaf_DeepSeek2 },
	{ "ClaudeEx3", "達人王みたいな弾幕", "", "", "Torpedo_Hymn", EnemyPat_Tatsujinou_Claude },
	{ "ClaudeEx4", "蜂をモチーフにした弾幕 アナザー", "", "", "Torpedo_Hymn", EnemyPat_Bee_Claude2 },
	{ "GeminiEx2", "闇符「ディマーケイション」LUNATIC", "", "", "Torpedo_Hymn", EnemyPat_Demarcation_Gemini },
	{ "GeminiEx3", "魔法のランプをモチーフにした弾幕", "", "", "Desert Lamp Pursuit", EnemyPat_MagicLamp_Gemini },
	{ "DeepSeek1", "幾何学的に美しい弾幕", "", "", "Chrome_Synapse", EnemyPat_Geometry_DeepSeek },
	{ "ChatGPT1", "幾何学的に美しい弾幕", "万華鏡リサージュ", "", "Chrome_Synapse", EnemyPat_Geometry_ChatGPT },
	{ "Gemini1", "幾何学的に美しい弾幕", "", "", "Chrome_Synapse", EnemyPat_Geometry_Gemini },
	{ "Grok1", "幾何学的に美しい弾幕", "", "", "Chrome_Synapse", EnemyPat_Geometry_Grok },
	{ "Sakana1", "幾何学的に美しい弾幕", "", "", "Chrome_Synapse", EnemyPat_Geometry_Sakana },
	{ "Claude1", "幾何学的に美しい弾幕", "フィボナッチ螺旋弾幕「ひまわり」", "", "Chrome_Synapse", EnemyPat_Geometry_Claude },
	{ "Qwen1", "幾何学的に美しい弾幕", "", "", "Chrome_Synapse", EnemyPat_Geometry_Qwen },
	{ "Vibe1", "幾何学的に美しい弾幕", "", "", "Chrome_Synapse", EnemyPat_Geometry_Vibe },
	{ "DeepSeek2", "避けていて楽しい弾幕", "", "", "Polished_Thunder", EnemyPat_Dodge_DeepSeek },
	{ "ChatGPT2", "避けていて楽しい弾幕", "誘導の狭間", "", "Polished_Thunder", EnemyPat_Dodge_ChatGPT },
	{ "Gemini2", "避けていて楽しい弾幕", "時限一斉収縮ターゲット弾「サイレンス・トラップ」", "", "Polished_Thunder", EnemyPat_Dodge_Gemini },
	{ "Grok2", "避けていて楽しい弾幕", "", "", "Polished_Thunder", EnemyPat_Dodge_Grok },
	{ "Sakana2", "避けていて楽しい弾幕", "", "", "Polished_Thunder", EnemyPat_Dodge_Sakana },
	{ "Claude2", "避けていて楽しい弾幕", "", "", "Polished_Thunder", EnemyPat_Dodge_Claude },
	{ "Qwen2", "避けていて楽しい弾幕", "", "", "Polished_Thunder", EnemyPat_Dodge_Qwen },
	{ "Vibe2", "避けていて楽しい弾幕", "", "", "Polished_Thunder", EnemyPat_Dodge_Vibe },
	{ "DeepSeek3", "見栄えのいい弾幕", "レインボースパイラル", "", "Chromed_Halo", EnemyPat_Beautiful_DeepSeek },
	{ "ChatGPT3", "見栄えのいい弾幕", "花渦輪舞", "", "Chromed_Halo", EnemyPat_Beautiful_ChatGPT },
	{ "Gemini3", "見栄えのいい弾幕", "", "", "Chromed_Halo", EnemyPat_Beautiful_Gemini },
	{ "Grok3", "見栄えのいい弾幕", "", "", "Chromed_Halo", EnemyPat_Beautiful_Grok },
	{ "Sakana3", "見栄えのいい弾幕", "", "", "Chromed_Halo", EnemyPat_Beautiful_Sakana },
	{ "Claude3", "見栄えのいい弾幕", "", "", "Chromed_Halo", EnemyPat_Beautiful_Claude },
	{ "Qwen3", "見栄えのいい弾幕", "", "", "Chromed_Halo", EnemyPat_Beautiful_Qwen },
	{ "Vibe3", "見栄えのいい弾幕", "", "", "Chromed_Halo", EnemyPat_Beautiful_Vibe },
	{ "DeepSeek4", "和風な弾幕", "", "", "Taiko_Lightning", EnemyPat_Japanese_DeepSeek },
	{ "ChatGPT4", "和風な弾幕", "花嵐扇舞", "", "Taiko_Lightning", EnemyPat_Japanese_ChatGPT },
	{ "Gemini4", "和風な弾幕", "", "", "Taiko_Lightning", EnemyPat_Japanese_Gemini },
	{ "Grok4", "和風な弾幕", "", "", "Taiko_Lightning", EnemyPat_Japanese_Grok },
	{ "Sakana4", "和風な弾幕", "", "", "Taiko_Lightning", EnemyPat_Japanese_Sakana },
	{ "Claude4", "和風な弾幕", "", "", "Taiko_Lightning", EnemyPat_Japanese_Claude },
	{ "Qwen4", "和風な弾幕", "", "", "Taiko_Lightning", EnemyPat_Japanese_Qwen },
	{ "Vibe4", "和風な弾幕", "", "", "Taiko_Lightning", EnemyPat_Japanese_Vibe },
	{ "DeepSeek5", "滝をモチーフにした弾幕", "", "", "Taiko_Lightning2", EnemyPat_Waterfall_DeepSeek },
	{ "ChatGPT5", "滝をモチーフにした弾幕", "蒼瀑「天泣の大瀑布」", "", "Taiko_Lightning2", EnemyPat_Waterfall_ChatGPT },
	{ "Gemini5", "滝をモチーフにした弾幕", "滝符『白糸の瀑布』", "", "Taiko_Lightning2", EnemyPat_Waterfall_Gemini },
	{ "Grok5", "滝をモチーフにした弾幕", "", "", "Taiko_Lightning2", EnemyPat_Waterfall_Grok },
	{ "Sakana5", "滝をモチーフにした弾幕", "", "", "Taiko_Lightning2", EnemyPat_Waterfall_Sakana },
	{ "Claude5", "滝をモチーフにした弾幕", "", "", "Taiko_Lightning2", EnemyPat_Waterfall_Claude },
	{ "Qwen5", "滝をモチーフにした弾幕", "", "", "Taiko_Lightning2", EnemyPat_Waterfall_Qwen },
	{ "Vibe5", "滝をモチーフにした弾幕", "", "", "Taiko_Lightning2", EnemyPat_Waterfall_Vibe },
	{ "DeepSeek6", "波と粒の境界", "", "", "Clockwork_Rush", EnemyPat_Namistubu_DeepSeek },
	{ "ChatGPT6", "波と粒の境界", "波際の粒界線", "", "Clockwork_Rush", EnemyPat_Namistubu_ChatGPT },
	{ "Gemini6", "波と粒の境界", "", "", "Clockwork_Rush", EnemyPat_Namistubu_Gemini },
	{ "Grok6", "波と粒の境界", "境符「回転する波と粒」", "", "Clockwork_Rush", EnemyPat_Namistubu_Grok },
	{ "Sakana6", "波と粒の境界", "", "", "Clockwork_Rush", EnemyPat_Namistubu_Sakana },
	{ "Claude6", "波と粒の境界", "", "", "Clockwork_Rush", EnemyPat_Namistubu_Claude },
	{ "Qwen6", "波と粒の境界", "", "", "Clockwork_Rush", EnemyPat_Namistubu_Qwen },
	{ "Vibe6", "波と粒の境界", "", "", "Clockwork_Rush", EnemyPat_Namitsubu_Vibe },
	{ "DeepSeek7", "彗星をモチーフにした弾幕", "", "", "Nebula_Pulse_Loop", EnemyPat_Comet_DeepSeek },
	{ "ChatGPT7", "彗星をモチーフにした弾幕", "尾を曳く蒼天の彗星", "", "Nebula_Pulse_Loop", EnemyPat_Comet_ChatGPT },
	{ "Gemini7", "彗星をモチーフにした弾幕", "", "", "Nebula_Pulse_Loop", EnemyPat_Comet_Gemini },
	{ "Grok7", "彗星をモチーフにした弾幕", "", "", "Nebula_Pulse_Loop", EnemyPat_Comet_Grok },
	{ "Sakana7", "彗星をモチーフにした弾幕", "", "", "Nebula_Pulse_Loop", EnemyPat_Comet_Sakana },
	{ "Claude7", "彗星をモチーフにした弾幕", "彗星の軌跡", "", "Nebula_Pulse_Loop", EnemyPat_Comet_Claude },
	{ "Qwen7", "彗星をモチーフにした弾幕", "", "", "Nebula_Pulse_Loop", EnemyPat_Comet_Qwen },
	{ "Vibe7", "彗星をモチーフにした弾幕", "", "", "Nebula_Pulse_Loop", EnemyPat_Comet_Vibe },
	{ "DeepSeek8", "雷をモチーフにした弾幕", "", "", "Clockwork_Rush2", EnemyPat_Thunder_DeepSeek },
	{ "ChatGPT8", "雷をモチーフにした弾幕", "雷鳴裂走（らいめいれっそう）", "", "Clockwork_Rush2", EnemyPat_Thunder_ChatGPT },
	{ "Gemini8", "雷をモチーフにした弾幕", "", "", "Clockwork_Rush2", EnemyPat_Thunder_Gemini },
	{ "Grok8", "雷をモチーフにした弾幕", "", "", "Clockwork_Rush2", EnemyPat_Thunder_Grok },
	{ "Sakana8", "雷をモチーフにした弾幕", "稲妻乱舞", "", "Clockwork_Rush2", EnemyPat_Thunder_Sakana },
	{ "Claude8", "雷をモチーフにした弾幕", "", "", "Clockwork_Rush2", EnemyPat_Thunder_Claude },
	{ "Qwen8", "雷をモチーフにした弾幕", "", "", "Clockwork_Rush2", EnemyPat_Thunder_Qwen },
	{ "Vibe8", "雷をモチーフにした弾幕", "", "", "Clockwork_Rush2", EnemyPat_Thunder_Vibe },
	{ "DeepSeek9", "吹雪をモチーフにした弾幕", "", "", "Whiteout_Loop", EnemyPat_Blizzard_DeepSeek },
	{ "ChatGPT9", "吹雪をモチーフにした弾幕", "白銀風雪・ブリザードヴェール", "", "Whiteout_Loop", EnemyPat_Blizzard_ChatGPT },
	{ "Gemini9", "吹雪をモチーフにした弾幕", "氷雪乱舞「ダイアモンドダスト」", "", "Whiteout_Loop", EnemyPat_Blizzard_Gemini },
	{ "Grok9", "吹雪をモチーフにした弾幕", "", "", "Whiteout_Loop", EnemyPat_Blizzard_Grok },
	{ "Sakana9", "吹雪をモチーフにした弾幕", "", "", "Whiteout_Loop", EnemyPat_Blizzard_Sakana },
	{ "Claude9", "吹雪をモチーフにした弾幕", "", "", "Whiteout_Loop", EnemyPat_Blizzard_Claude },
	{ "Qwen9", "吹雪をモチーフにした弾幕", "", "", "Whiteout_Loop", EnemyPat_Blizzard_Qwen },
	{ "Vibe9", "吹雪をモチーフにした弾幕", "", "", "Whiteout_Loop", EnemyPat_Blizzard_Vibe },
	{ "DeepSeek10", "竜をモチーフにした弾幕", "", "", "Dragonforge_Overture", EnemyPat_Dragon_DeepSeek },
	{ "ChatGPT10", "竜をモチーフにした弾幕", "龍脈崩天（りゅうみゃくほうてん）", "", "Dragonforge_Overture", EnemyPat_Dragon_ChatGPT },
	{ "Gemini10", "竜をモチーフにした弾幕", "", "", "Dragonforge_Overture", EnemyPat_Dragon_Gemini },
	{ "Grok10", "竜をモチーフにした弾幕", "炎竜の息吹 ～ウネリの鱗～", "", "Dragonforge_Overture", EnemyPat_Dragon_Grok },
	{ "Sakana10", "竜をモチーフにした弾幕", "", "", "Dragonforge_Overture", EnemyPat_Dragon_Sakana },
	{ "Claude10", "竜をモチーフにした弾幕", "", "", "Dragonforge_Overture", EnemyPat_Dragon_Claude },
	{ "Qwen10", "竜をモチーフにした弾幕", "", "", "Dragonforge_Overture", EnemyPat_Dragon_Qwen },
	{ "Vibe10", "竜をモチーフにした弾幕", "", "", "Dragonforge_Overture", EnemyPat_Dragon_Vibe },
	{ "DeepSeek11", "はかいこうせんをモチーフにした弾幕", "", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_DeepSeek },
	{ "ChatGPT11", "はかいこうせんをモチーフにした弾幕", "終焉光線「はかいこうせん・アルティメットブレイク」", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_ChatGPT },
	{ "Gemini11", "はかいこうせんをモチーフにした弾幕", "ハイパーチャージ・ブラスト", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Gemini },
	{ "Grok11", "はかいこうせんをモチーフにした弾幕", "", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Grok },
	{ "Sakana11", "はかいこうせんをモチーフにした弾幕", "", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Sakana },
	{ "Claude11", "はかいこうせんをモチーフにした弾幕", "", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Claude },
	{ "Qwen11", "はかいこうせんをモチーフにした弾幕", "", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Qwen },
	{ "Vibe11", "はかいこうせんをモチーフにした弾幕", "", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Vibe },
	{ "DeepSeek12", "太陽をモチーフにした弾幕", "", "", "Scorching_Danmaku", EnemyPat_Sun_DeepSeek },
	{ "ChatGPT12", "太陽をモチーフにした弾幕", "天照・紅炎輪廻（てんしょう・こうえんりんね）", "", "Scorching_Danmaku", EnemyPat_Sun_ChatGPT },
	{ "Gemini12", "太陽をモチーフにした弾幕", "", "", "Scorching_Danmaku", EnemyPat_Sun_Gemini },
	{ "Grok12", "太陽をモチーフにした弾幕", "", "", "Scorching_Danmaku", EnemyPat_Sun_Grok },
	{ "Sakana12", "太陽をモチーフにした弾幕", "", "", "Scorching_Danmaku", EnemyPat_Sun_Sakana },
	{ "Claude12", "太陽をモチーフにした弾幕", "", "", "Scorching_Danmaku", EnemyPat_Sun_Claude },
	{ "Qwen12", "太陽をモチーフにした弾幕", "太陽のフレアとコロナ", "", "Scorching_Danmaku", EnemyPat_Sun_Qwen },
	{ "Vibe12", "太陽をモチーフにした弾幕", "", "", "Scorching_Danmaku", EnemyPat_Sun_Vibe },
	{ "DeepSeek13", "はっぱカッターをモチーフにした弾幕", "双葉嵐刃（ふたばらんじん）", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_DeepSeek },
	{ "ChatGPT13", "はっぱカッターをモチーフにした弾幕", "翠嵐刃葉「リーフ・テンペスト」", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_ChatGPT },
	{ "Gemini13", "はっぱカッターをモチーフにした弾幕", "", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Gemini },
	{ "Grok13", "はっぱカッターをモチーフにした弾幕", "", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Grok },
	{ "Sakana13", "はっぱカッターをモチーフにした弾幕", "", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Sakana },
	{ "Claude13", "はっぱカッターをモチーフにした弾幕", "", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Claude },
	{ "Qwen13", "はっぱカッターをモチーフにした弾幕", "", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Qwen },
	{ "Vibe13", "はっぱカッターをモチーフにした弾幕", "", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Vibe },
	{ "DeepSeek14", "毒をモチーフにした弾幕", "", "", "Toxic_Clockwork", EnemyPat_Poison_DeepSeek },
	{ "ChatGPT14", "毒をモチーフにした弾幕", "毒華散華（どくかさんげ）", "", "Toxic_Clockwork", EnemyPat_Poison_ChatGPT },
	{ "Gemini14", "毒をモチーフにした弾幕", "", "", "Toxic_Clockwork", EnemyPat_Poison_Gemini },
	{ "Grok14", "毒をモチーフにした弾幕", "", "", "Toxic_Clockwork", EnemyPat_Poison_Grok },
	{ "Sakana14", "毒をモチーフにした弾幕", "", "", "Toxic_Clockwork", EnemyPat_Poison_Sakana },
	{ "Claude14", "毒をモチーフにした弾幕", "毒華乱舞", "", "Toxic_Clockwork", EnemyPat_Poison_Claude },
	{ "Qwen14", "毒をモチーフにした弾幕", "", "", "Toxic_Clockwork", EnemyPat_Poison_Qwen },
	{ "Vibe14", "毒をモチーフにした弾幕", "", "", "Toxic_Clockwork", EnemyPat_Poison_Vibe },
	{ "DeepSeek15", "洗濯機をモチーフにした弾幕", "", "", "Taiko_Lightning3", EnemyPat_WashingMachine_DeepSeek },
	{ "ChatGPT15", "洗濯機をモチーフにした弾幕", "超高速洗浄「蒼流・脱水スピン」", "", "Taiko_Lightning3", EnemyPat_WashingMachine_ChatGPT },
	{ "Gemini15", "洗濯機をモチーフにした弾幕", "回転水流と洗剤泡の全自動脱水弾幕", "", "Taiko_Lightning3", EnemyPat_WashingMachine_Gemini },
	{ "Grok15", "洗濯機をモチーフにした弾幕", "", "", "Taiko_Lightning3", EnemyPat_WashingMachine_Grok },
	{ "Sakana15", "洗濯機をモチーフにした弾幕", "", "", "Taiko_Lightning3", EnemyPat_WashingMachine_Sakana },
	{ "Claude15", "洗濯機をモチーフにした弾幕", "", "", "Taiko_Lightning3", EnemyPat_WashingMachine_Claude },
	{ "Qwen15", "洗濯機をモチーフにした弾幕", "", "", "Taiko_Lightning3", EnemyPat_WashingMachine_Qwen },
	{ "Vibe15", "洗濯機をモチーフにした弾幕", "", "", "Taiko_Lightning3", EnemyPat_WashingMachine_Vibe },
	{ "DeepSeek16", "囲碁をモチーフにした弾幕", "", "", "Bullet_Hell_Shrine", EnemyPat_Go_DeepSeek },
	{ "ChatGPT16", "囲碁をモチーフにした弾幕", "黒白星羅（こくびゃくせいら） ～盤上に舞う無限の一手～", "", "Bullet_Hell_Shrine", EnemyPat_Go_ChatGPT },
	{ "Gemini16", "囲碁をモチーフにした弾幕", "囲碁弾幕「布石と崩壊」", "", "Bullet_Hell_Shrine", EnemyPat_Go_Gemini },
	{ "Grok16", "囲碁をモチーフにした弾幕", "", "", "Bullet_Hell_Shrine", EnemyPat_Go_Grok },
	{ "Sakana16", "囲碁をモチーフにした弾幕", "", "", "Bullet_Hell_Shrine", EnemyPat_Go_Sakana },
	{ "Claude16", "囲碁をモチーフにした弾幕", "", "", "Bullet_Hell_Shrine", EnemyPat_Go_Claude },
	{ "Qwen16", "囲碁をモチーフにした弾幕", "", "", "Bullet_Hell_Shrine", EnemyPat_Go_Qwen },
	{ "Vibe16", "囲碁をモチーフにした弾幕", "", "", "Bullet_Hell_Shrine", EnemyPat_Go_Vibe },
	{ "DeepSeek17", "紅葉をモチーフにした弾幕", "", "", "Stormleaf_Skyshot", EnemyPat_Maple_DeepSeek },
	{ "ChatGPT17", "紅葉をモチーフにした弾幕", "紅葉狩・秋風乱舞（もみじがり・あきかぜらんぶ）", "", "Stormleaf_Skyshot", EnemyPat_Maple_ChatGPT },
	{ "Gemini17", "紅葉をモチーフにした弾幕", "紅葉の舞 ～ 舞い散る秋の疾風", "", "Stormleaf_Skyshot", EnemyPat_Maple_Gemini },
	{ "Grok17", "紅葉をモチーフにした弾幕", "", "", "Stormleaf_Skyshot", EnemyPat_Maple_Grok },
	{ "Sakana17", "紅葉をモチーフにした弾幕", "", "", "Stormleaf_Skyshot", EnemyPat_Maple_Sakana },
	{ "Claude17", "紅葉をモチーフにした弾幕", "", "", "Stormleaf_Skyshot", EnemyPat_Maple_Claude },
	{ "Qwen17", "紅葉をモチーフにした弾幕", "", "", "Stormleaf_Skyshot", EnemyPat_Maple_Qwen },
	{ "Vibe17", "紅葉をモチーフにした弾幕", "", "", "Stormleaf_Skyshot", EnemyPat_Maple_Vibe },
	{ "DeepSeek18", "クモの巣をモチーフにした弾幕", "", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_DeepSeek },
	{ "ChatGPT18", "クモの巣をモチーフにした弾幕", "絡繰蜘蛛網「リサージュ・スパイダーウェブ」", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_ChatGPT },
	{ "Gemini18", "クモの巣をモチーフにした弾幕", "捕食者の拘束陣 ～ Spider Web Trap", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Gemini },
	{ "Grok18", "クモの巣をモチーフにした弾幕", "", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Grok },
	{ "Sakana18", "クモの巣をモチーフにした弾幕", "", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Sakana },
	{ "Claude18", "クモの巣をモチーフにした弾幕", "", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Claude },
	{ "Qwen18", "クモの巣をモチーフにした弾幕", "", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Qwen },
	{ "Vibe18", "クモの巣をモチーフにした弾幕", "", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Vibe },
	{ "DeepSeek19", "双曲線をモチーフにした弾幕", "", "", "Clockwork_Rush3", EnemyPat_Hyperbola_DeepSeek },
	{ "ChatGPT19", "双曲線をモチーフにした弾幕", "双曲線・アポロニアンカタストロフィー", "", "Clockwork_Rush3", EnemyPat_Hyperbola_ChatGPT },
	{ "Gemini19", "双曲線をモチーフにした弾幕", "", "", "Clockwork_Rush3", EnemyPat_Hyperbola_Gemini },
	{ "Grok19", "双曲線をモチーフにした弾幕", "", "", "Clockwork_Rush3", EnemyPat_Hyperbola_Grok },
	{ "Sakana19", "双曲線をモチーフにした弾幕", "", "", "Clockwork_Rush3", EnemyPat_Hyperbola_Sakana },
	{ "Claude19", "双曲線をモチーフにした弾幕", "", "", "Clockwork_Rush3", EnemyPat_Hyperbola_Claude },
	{ "Qwen19", "双曲線をモチーフにした弾幕", "双曲線符「ローテティング・ハイパーボラ」", "", "Clockwork_Rush3", EnemyPat_Hyperbola_Qwen },
	{ "Vibe19", "双曲線をモチーフにした弾幕", "", "", "Clockwork_Rush3", EnemyPat_Hyperbola_Vibe },
	{ "DeepSeek20", "砂時計をモチーフにした弾幕", "", "", "Youma", EnemyPat_Hourglass_DeepSeek },
	{ "ChatGPT20", "砂時計をモチーフにした弾幕", "時刻砂界（じこくさかい）～クロノ・アワーグラス～", "", "Youma", EnemyPat_Hourglass_ChatGPT },
	{ "Gemini20", "砂時計をモチーフにした弾幕", "時砂の回廊 - Chrono Hourglass", "", "Youma", EnemyPat_Hourglass_Gemini },
	{ "Grok20", "砂時計をモチーフにした弾幕", "", "", "Youma", EnemyPat_Hourglass_Grok },
	{ "Sakana20", "砂時計をモチーフにした弾幕", "", "", "Youma", EnemyPat_Hourglass_Sakana },
	{ "Claude20", "砂時計をモチーフにした弾幕", "", "", "Youma", EnemyPat_Hourglass_Claude },
	{ "Qwen20", "砂時計をモチーフにした弾幕", "", "", "Youma", EnemyPat_Hourglass_Qwen },
	{ "Vibe20", "砂時計をモチーフにした弾幕", "", "", "Youma", EnemyPat_Hourglass_Vibe },
	{ "DeepSeek21", "火山をモチーフにした弾幕", "", "", "Molten_Crown", EnemyPat_Volcano_DeepSeek },
	{ "ChatGPT21", "火山をモチーフにした弾幕", "噴火「紅蓮昇華・灼熱の火山雨」", "", "Molten_Crown", EnemyPat_Volcano_ChatGPT },
	{ "Gemini21", "火山をモチーフにした弾幕", "大噴火「マグマクライシス」", "", "Molten_Crown", EnemyPat_Volcano_Gemini },
	{ "Grok21", "火山をモチーフにした弾幕", "", "", "Molten_Crown", EnemyPat_Volcano_Grok },
	{ "Sakana21", "火山をモチーフにした弾幕", "", "", "Molten_Crown", EnemyPat_Volcano_Sakana },
	{ "Claude21", "火山をモチーフにした弾幕", "", "", "Molten_Crown", EnemyPat_Volcano_Claude },
	{ "Qwen21", "火山をモチーフにした弾幕", "", "", "Molten_Crown", EnemyPat_Volcano_Qwen },
	{ "Vibe21", "火山をモチーフにした弾幕", "", "", "Molten_Crown", EnemyPat_Volcano_Vibe },
	{ "DeepSeek22", "音ゲーをモチーフにした弾幕", "リズムノーツ・レイン", "", "Organ_Sprint", EnemyPat_RhythmGame_DeepSeek },
	{ "ChatGPT22", "音ゲーをモチーフにした弾幕", "譜面奏弾「リズム・オブ・レイヴ」", "", "Organ_Sprint", EnemyPat_RhythmGame_ChatGPT },
	{ "Gemini22", "音ゲーをモチーフにした弾幕", "", "", "Organ_Sprint", EnemyPat_RhythmGame_Gemini },
	{ "Grok22", "音ゲーをモチーフにした弾幕", "", "", "Organ_Sprint", EnemyPat_RhythmGame_Grok },
	{ "Sakana22", "音ゲーをモチーフにした弾幕", "", "", "Organ_Sprint", EnemyPat_RhythmGame_Sakana },
	{ "Claude22", "音ゲーをモチーフにした弾幕", "", "", "Organ_Sprint", EnemyPat_RhythmGame_Claude },
	{ "Qwen22", "音ゲーをモチーフにした弾幕", "", "", "Organ_Sprint", EnemyPat_RhythmGame_Qwen },
	{ "Vibe22", "音ゲーをモチーフにした弾幕", "", "", "Organ_Sprint", EnemyPat_RhythmGame_Vibe },
	{ "DeepSeek23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "", "Fractal_Boss", EnemyPat_Sierpinski_DeepSeek },
	{ "ChatGPT23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "無限三角牢獄（インフィニット・トライアングル）", "", "Fractal_Boss", EnemyPat_Sierpinski_ChatGPT },
	{ "Gemini23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "回転拡縮シェルピンスキーのギャスケット", "", "Fractal_Boss", EnemyPat_Sierpinski_Gemini },
	{ "Grok23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "", "Fractal_Boss", EnemyPat_Sierpinski_Grok },
	{ "Sakana23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "", "Fractal_Boss", EnemyPat_Sierpinski_Sakana },
	{ "Claude23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "", "Fractal_Boss", EnemyPat_Sierpinski_Claude },
	{ "Qwen23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "", "Fractal_Boss", EnemyPat_Sierpinski_Qwen },
	{ "Vibe23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "", "Fractal_Boss", EnemyPat_Sierpinski_Vibe },
	{ "DeepSeek24", "メビウスの帯をモチーフにした弾幕", "メビウスのリボン", "", "Cosmic_Mobius", EnemyPat_Mobius_DeepSeek },
	{ "ChatGPT24", "メビウスの帯をモチーフにした弾幕", "輪廻する虚無帯（メビウス・エターナル）", "", "Cosmic_Mobius", EnemyPat_Mobius_ChatGPT },
	{ "Gemini24", "メビウスの帯をモチーフにした弾幕", "", "", "Cosmic_Mobius", EnemyPat_Mobius_Gemini },
	{ "Grok24", "メビウスの帯をモチーフにした弾幕", "", "", "Cosmic_Mobius", EnemyPat_Mobius_Grok },
	{ "Sakana24", "メビウスの帯をモチーフにした弾幕", "", "", "Cosmic_Mobius", EnemyPat_Mobius_Sakana },
	{ "Claude24", "メビウスの帯をモチーフにした弾幕", "", "", "Cosmic_Mobius", EnemyPat_Mobius_Claude },
	{ "Qwen24", "メビウスの帯をモチーフにした弾幕", "", "", "Cosmic_Mobius", EnemyPat_Mobius_Qwen },
	{ "Vibe24", "メビウスの帯をモチーフにした弾幕", "", "", "Cosmic_Mobius", EnemyPat_Mobius_Vibe },
	{ "DeepSeek25", "扇風機をモチーフにした弾幕", "", "", "Frantic_Pulse", EnemyPat_ElectricFan_DeepSeek },
	{ "ChatGPT25", "扇風機をモチーフにした弾幕", "送風三連扇", "", "Frantic_Pulse", EnemyPat_ElectricFan_ChatGPT },
	{ "Gemini25", "扇風機をモチーフにした弾幕", "", "", "Frantic_Pulse", EnemyPat_ElectricFan_Gemini },
	{ "Grok25", "扇風機をモチーフにした弾幕", "", "", "Frantic_Pulse", EnemyPat_ElectricFan_Grok },
	{ "Sakana25", "扇風機をモチーフにした弾幕", "", "", "Frantic_Pulse", EnemyPat_ElectricFan_Sakana },
	{ "Claude25", "扇風機をモチーフにした弾幕", "", "", "Frantic_Pulse", EnemyPat_ElectricFan_Claude },
	{ "Qwen25", "扇風機をモチーフにした弾幕", "", "", "Frantic_Pulse", EnemyPat_ElectricFan_Qwen },
	{ "Vibe25", "扇風機をモチーフにした弾幕", "", "", "Frantic_Pulse", EnemyPat_ElectricFan_Vibe },
	{ "DeepSeek26", "文字を活用した弾幕", "", "", "Shamisen_Run", EnemyPat_Moji_DeepSeek },
	{ "ChatGPT26", "文字を活用した弾幕", "筆文字弾幕", "", "Shamisen_Run", EnemyPat_Moji_ChatGPT },
	{ "Gemini26", "文字を活用した弾幕", "", "", "Shamisen_Run", EnemyPat_Moji_Gemini },
	{ "Grok26", "文字を活用した弾幕", "", "", "Shamisen_Run", EnemyPat_Moji_Grok },
	{ "Sakana26", "文字を活用した弾幕", "弾・再集結", "", "Shamisen_Run", EnemyPat_Moji_Sakana },
	{ "Claude26", "文字を活用した弾幕", "", "", "Shamisen_Run", EnemyPat_Moji_Claude },
	{ "Qwen26", "文字を活用した弾幕", "", "", "Shamisen_Run", EnemyPat_Moji_Qwen },
	{ "Vibe26", "文字を活用した弾幕", "", "", "Shamisen_Run", EnemyPat_Moji_Vibe },
	{ "DeepSeek27", "手裏剣をモチーフにした弾幕", "", "", "Gongline_Riot", EnemyPat_Shuriken_DeepSeek },
	{ "ChatGPT27", "手裏剣をモチーフにした弾幕", "旋風手裏剣「散華の陣」", "", "Gongline_Riot", EnemyPat_Shuriken_ChatGPT },
	{ "Gemini27", "手裏剣をモチーフにした弾幕", "旋風・影分身十字", "", "Gongline_Riot", EnemyPat_Shuriken_Gemini },
	{ "Grok27", "手裏剣をモチーフにした弾幕", "", "", "Gongline_Riot", EnemyPat_Shuriken_Grok },
	{ "Sakana27", "手裏剣をモチーフにした弾幕", "", "", "Gongline_Riot", EnemyPat_Shuriken_Sakana },
	{ "Claude27", "手裏剣をモチーフにした弾幕", "", "", "Gongline_Riot", EnemyPat_Shuriken_Claude },
	{ "Qwen27", "手裏剣をモチーフにした弾幕", "", "", "Gongline_Riot", EnemyPat_Shuriken_Qwen },
	{ "Vibe27", "手裏剣をモチーフにした弾幕", "", "", "Gongline_Riot", EnemyPat_Shuriken_Vibe },
	{ "DeepSeek28", "金閣寺の一枚天井", "", "", "Gongline_Riot2", EnemyPat_Kinkakuji_DeepSeek },
	{ "ChatGPT28", "金閣寺の一枚天井", "新難題「金閣楼の落天回廊」", "", "Gongline_Riot2", EnemyPat_Kinkakuji_ChatGPT },
	{ "Gemini28", "金閣寺の一枚天井", "", "", "Gongline_Riot2", EnemyPat_Kinkakuji_Gemini },
	{ "Grok28", "金閣寺の一枚天井", "", "", "Gongline_Riot2", EnemyPat_Kinkakuji_Grok },
	{ "Sakana28", "金閣寺の一枚天井", "", "", "Gongline_Riot2", EnemyPat_Kinkakuji_Sakana },
	{ "Claude28", "金閣寺の一枚天井", "絢爛「煌金の板と旋弾の底」", "", "Gongline_Riot2", EnemyPat_Kinkakuji_Claude },
	{ "Qwen28", "金閣寺の一枚天井", "", "", "Gongline_Riot2", EnemyPat_Kinkakuji_Qwen },
	{ "Vibe28", "金閣寺の一枚天井", "", "", "Gongline_Riot2", EnemyPat_Kinkakuji_Vibe },
	{ "DeepSeek29", "シャボン玉をモチーフにした弾幕", "", "", "Bubble_Horizon", EnemyPat_SoapBubbles_DeepSeek },
	{ "ChatGPT29", "シャボン玉をモチーフにした弾幕", "泡沫「虹色泡沫庭園（バブル・ガーデン）」", "", "Bubble_Horizon", EnemyPat_SoapBubbles_ChatGPT },
	{ "Gemini29", "シャボン玉をモチーフにした弾幕", "ソープバブル・トラップ", "", "Bubble_Horizon", EnemyPat_SoapBubbles_Gemini },
	{ "Grok29", "シャボン玉をモチーフにした弾幕", "", "", "Bubble_Horizon", EnemyPat_SoapBubbles_Grok },
	{ "Sakana29", "シャボン玉をモチーフにした弾幕", "", "", "Bubble_Horizon", EnemyPat_SoapBubbles_Sakana },
	{ "Claude29", "シャボン玉をモチーフにした弾幕", "", "", "Bubble_Horizon", EnemyPat_SoapBubbles_Claude },
	{ "Qwen29", "シャボン玉をモチーフにした弾幕", "", "", "Bubble_Horizon", EnemyPat_SoapBubbles_Qwen },
	{ "Vibe29", "シャボン玉をモチーフにした弾幕", "", "", "Bubble_Horizon", EnemyPat_SoapBubbles_Vibe },
	{ "DeepSeek30", "ショットガンをモチーフにした弾幕", "", "", "Torque_Anthem", EnemyPat_Shotgun_DeepSeek },
	{ "ChatGPT30", "ショットガンをモチーフにした弾幕", "散弾爆裂「ラピッド・バレル」", "", "Torque_Anthem", EnemyPat_Shotgun_ChatGPT },
	{ "Gemini30", "ショットガンをモチーフにした弾幕", "クロースレンジ・バースト（近接信管の散弾）", "", "Torque_Anthem", EnemyPat_Shotgun_Gemini },
	{ "Grok30", "ショットガンをモチーフにした弾幕", "", "", "Torque_Anthem", EnemyPat_Shotgun_Grok },
	{ "Sakana30", "ショットガンをモチーフにした弾幕", "", "", "Torque_Anthem", EnemyPat_Shotgun_Sakana },
	{ "Claude30", "ショットガンをモチーフにした弾幕", "", "", "Torque_Anthem", EnemyPat_Shotgun_Claude },
	{ "Qwen30", "ショットガンをモチーフにした弾幕", "", "", "Torque_Anthem", EnemyPat_Shotgun_Qwen },
	{ "Kimi30", "ショットガンをモチーフにした弾幕", "", "", "Torque_Anthem", EnemyPat_Shotgun_Kimi },
	{ "DeepSeek31", "戻り弾幕", "", "", "Youma2", EnemyPat_Reverse_DeepSeek },
	{ "ChatGPT31", "戻り弾幕", "輪廻帰弾「ブーメラン・エクリプス」", "", "Youma2", EnemyPat_Reverse_ChatGPT },
	{ "Gemini31", "戻り弾幕", "", "", "Youma2", EnemyPat_Reverse_Gemini },
	{ "Grok31", "戻り弾幕", "", "", "Youma2", EnemyPat_Reverse_Grok },
	{ "Sakana31", "戻り弾幕", "", "", "Youma2", EnemyPat_Reverse_Sakana },
	{ "Claude31", "戻り弾幕", "", "", "Youma2", EnemyPat_Reverse_Claude },
	{ "Qwen31", "戻り弾幕", "", "", "Youma2", EnemyPat_Reverse_Qwen },
	{ "Kimi31", "戻り弾幕", "還り道（かえりみち）", "", "Youma2", EnemyPat_Reverse_Kimi },
	{ "DeepSeek32", "ボンバーマンをモチーフにした弾幕", "", "", "Pixel_Victory_Run", EnemyPat_Bomberman_DeepSeek },
	{ "ChatGPT32", "ボンバーマンをモチーフにした弾幕", "爆炎迷宮「ボム・パニック・クロス」", "", "Pixel_Victory_Run", EnemyPat_Bomberman_ChatGPT },
	{ "Gemini32", "ボンバーマンをモチーフにした弾幕", "ディレイド・クロス・ボンバー", "", "Pixel_Victory_Run", EnemyPat_Bomberman_Gemini },
	{ "Grok32", "ボンバーマンをモチーフにした弾幕", "", "", "Pixel_Victory_Run", EnemyPat_Bomberman_Grok },
	{ "Sakana32", "ボンバーマンをモチーフにした弾幕", "", "", "Pixel_Victory_Run", EnemyPat_Bomberman_Sakana },
	{ "Claude32", "ボンバーマンをモチーフにした弾幕", "", "", "Pixel_Victory_Run", EnemyPat_Bomberman_Claude },
	{ "Qwen32", "ボンバーマンをモチーフにした弾幕", "", "", "Pixel_Victory_Run", EnemyPat_Bomberman_Qwen },
	{ "Kimi32", "ボンバーマンをモチーフにした弾幕", "", "", "Pixel_Victory_Run", EnemyPat_Bomberman_Kimi },
	{ "DeepSeek33", "回避不可能な弾幕", "", "", "Torpedo_Hymn", EnemyPat_Unavoidable_DeepSeek },
	{ "ChatGPT33", "回避不可能な弾幕", "", "", "Torpedo_Hymn", EnemyPat_Unavoidable_ChatGPT },
	{ "Gemini33", "回避不可能な弾幕", "網羅「全方位格子陣 -理（ことわり）の終わり-」", "", "Clockwork Panic Run", EnemyPat_Unavoidable_Gemini },
	{ "Grok33", "回避不可能な弾幕", "絶対回避不能「混沌の三重獄」", "", "Ryukyu Neon Rush", EnemyPat_Unavoidable_Grok },
	{ "Sakana33", "回避不可能な弾幕", "", "", "Torpedo_Hymn", EnemyPat_Unavoidable_Sakana },
	{ "Claude33", "回避不可能な弾幕", "絶対回避不可能", "", "Torpedo_Hymn", EnemyPat_Unavoidable_Claude },
	{ "Qwen33", "回避不可能な弾幕", "", "", "Torpedo_Hymn", EnemyPat_Unavoidable_Qwen },
	{ "Kimi33", "回避不可能な弾幕", "", "", "Torpedo_Hymn", EnemyPat_Unavoidable_Kimi },
	{ "DeepSeek34", "マッチをモチーフにした弾幕", "", "", "Kagura_Storm", EnemyPat_Match_DeepSeek },
	{ "ChatGPT34", "マッチをモチーフにした弾幕", "擦火点（さっかてん）", "", "Kagura_Storm", EnemyPat_Match_ChatGPT },
	{ "Gemini34", "マッチをモチーフにした弾幕", "", "", "Kagura_Storm", EnemyPat_Match_Gemini },
	{ "Grok34", "マッチをモチーフにした弾幕", "", "", "Kagura_Storm", EnemyPat_Match_Grok },
	{ "Sakana34", "マッチをモチーフにした弾幕", "", "", "Kagura_Storm", EnemyPat_Match_Sakana },
	{ "Claude34", "マッチをモチーフにした弾幕", "", "", "Kagura_Storm", EnemyPat_Match_Claude },
	{ "Qwen34", "マッチをモチーフにした弾幕", "", "", "Kagura_Storm", EnemyPat_Match_Qwen },
	{ "Kimi34", "マッチをモチーフにした弾幕", "", "", "Kagura_Storm", EnemyPat_Match_Kimi },
	{ "DeepSeek35", "ワインダーを活用した弾幕", "", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_DeepSeek },
	{ "ChatGPT35", "ワインダーを活用した弾幕", "蛇腹双螺旋（ジャバラ・ツインスパイラル）", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_ChatGPT },
	{ "Gemini35", "ワインダーを活用した弾幕", "", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Gemini },
	{ "Grok35", "ワインダーを活用した弾幕", "", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Grok },
	{ "Sakana35", "ワインダーを活用した弾幕", "", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Sakana },
	{ "Claude35", "ワインダーを活用した弾幕", "渦墨(うずずみ)", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Claude },
	{ "Qwen35", "ワインダーを活用した弾幕", "", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Qwen },
	{ "Kimi35", "ワインダーを活用した弾幕", "", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Kimi },
	{ "DeepSeek36", "ポップコーンをモチーフにした弾幕", "", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_DeepSeek },
	{ "ChatGPT36", "ポップコーンをモチーフにした弾幕", "爆ぜる黄金粒 - ポップコーン・カーニバル", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_ChatGPT },
	{ "Gemini36", "ポップコーンをモチーフにした弾幕", "", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_Gemini },
	{ "Grok36", "ポップコーンをモチーフにした弾幕", "", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_Grok },
	{ "Sakana36", "ポップコーンをモチーフにした弾幕", "", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_Sakana },
	{ "Claude36", "ポップコーンをモチーフにした弾幕", "爆ぜる粒、跳ねる音 ― ポップコーン・ケトル", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_Claude },
	{ "Qwen36", "ポップコーンをモチーフにした弾幕", "", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_Qwen },
	{ "Kimi36", "ポップコーンをモチーフにした弾幕", "", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_Kimi },
	{ "DeepSeek37", "立体的に見える弾幕", "", "", "Sphere_Breaker", EnemyPat_3D_DeepSeek },
	{ "ChatGPT37", "立体的に見える弾幕", "螺旋虚洞「アビス・スパイラル・コリドー」", "", "Sphere_Breaker", EnemyPat_3D_ChatGPT },
	{ "Gemini37", "立体的に見える弾幕", "", "", "Sphere_Breaker", EnemyPat_3D_Gemini },
	{ "Grok37", "立体的に見える弾幕", "", "", "Sphere_Breaker", EnemyPat_3D_Grok },
	{ "Sakana37", "立体的に見える弾幕", "", "", "Sphere_Breaker", EnemyPat_3D_Sakana },
	{ "Claude37", "立体的に見える弾幕", "深宵環（しんしょうかん）", "", "Sphere_Breaker", EnemyPat_3D_Claude },
	{ "Qwen37", "立体的に見える弾幕", "", "", "Sphere_Breaker", EnemyPat_3D_Qwen },
	{ "Kimi37", "立体的に見える弾幕", "", "", "Sphere_Breaker", EnemyPat_3D_Kimi },
	{ "DeepSeek38", "レーザーを活用した弾幕", "", "", "Cage_Of_Lasers", EnemyPat_Laser_DeepSeek },
	{ "ChatGPT38", "レーザーを活用した弾幕", "機械仕掛けの光織陣（レーザー・ルーム）", "", "Cage_Of_Lasers", EnemyPat_Laser_ChatGPT },
	{ "Gemini38", "レーザーを活用した弾幕", "カッティング・ケージ（裁断される檻）", "", "Cage_Of_Lasers", EnemyPat_Laser_Gemini },
	{ "Grok38", "レーザーを活用した弾幕", "", "", "Cage_Of_Lasers", EnemyPat_Laser_Grok },
	{ "Sakana38", "レーザーを活用した弾幕", "", "", "Cage_Of_Lasers", EnemyPat_Laser_Sakana },
	{ "Claude38", "レーザーを活用した弾幕", "", "", "Cage_Of_Lasers", EnemyPat_Laser_Claude },
	{ "Qwen38", "レーザーを活用した弾幕", "", "", "Cage_Of_Lasers", EnemyPat_Laser_Qwen },
	{ "Kimi38", "レーザーを活用した弾幕", "", "", "Cage_Of_Lasers", EnemyPat_Laser_Kimi },
	{ "DeepSeek39", "インベーダーゲームをモチーフにした弾幕", "", "", "Quiet_Opening", EnemyPat_Invader_DeepSeek },
	{ "ChatGPT39", "インベーダーゲームをモチーフにした弾幕", "侵略編隊『ドットファランクス』", "", "Quiet_Opening", EnemyPat_Invader_ChatGPT },
	{ "Gemini39", "インベーダーゲームをモチーフにした弾幕", "", "", "Quiet_Opening", EnemyPat_Invader_Gemini },
	{ "Grok39", "インベーダーゲームをモチーフにした弾幕", "", "", "Quiet_Opening", EnemyPat_Invader_Grok },
	{ "Sakana39", "インベーダーゲームをモチーフにした弾幕", "", "", "Quiet_Opening", EnemyPat_Invader_Sakana },
	{ "Claude39", "インベーダーゲームをモチーフにした弾幕", "", "", "Quiet_Opening", EnemyPat_Invader_Claude },
	{ "Qwen39", "インベーダーゲームをモチーフにした弾幕", "", "", "Quiet_Opening", EnemyPat_Invader_Qwen },
	{ "Kimi39", "インベーダーゲームをモチーフにした弾幕", "", "", "Quiet_Opening", EnemyPat_Invader_Kimi },
	{ "DeepSeek40", "二重振り子をモチーフにした弾幕", "", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_DeepSeek },
	{ "ChatGPT40", "二重振り子をモチーフにした弾幕", "双鎖振動「カオス・ペンデュラム」", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_ChatGPT },
	{ "Gemini40", "二重振り子をモチーフにした弾幕", "カオス・ペンデュラム", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_Gemini },
	{ "Grok40", "二重振り子をモチーフにした弾幕", "", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_Grok },
	{ "Sakana40", "二重振り子をモチーフにした弾幕", "", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_Sakana },
	{ "Claude40", "二重振り子をモチーフにした弾幕", "", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_Claude },
	{ "Qwen40", "二重振り子をモチーフにした弾幕", "", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_Qwen },
	{ "Kimi40", "二重振り子をモチーフにした弾幕", "", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_Kimi },
	{ "DeepSeek41", "ブロック崩しをモチーフにした弾幕", "バウンド・カタストロフ", "", "Quiet_Opening2", EnemyPat_BlockBreak_DeepSeek },
	{ "ChatGPT41", "ブロック崩しをモチーフにした弾幕", "ブロック崩壊領域 - リバウンド・カタストロフィ", "", "Quiet_Opening2", EnemyPat_BlockBreak_ChatGPT },
	{ "Gemini41", "ブロック崩しをモチーフにした弾幕", "", "", "Quiet_Opening2", EnemyPat_BlockBreak_Gemini },
	{ "Grok41", "ブロック崩しをモチーフにした弾幕", "", "", "Quiet_Opening2", EnemyPat_BlockBreak_Grok },
	{ "Sakana41", "ブロック崩しをモチーフにした弾幕", "", "", "Quiet_Opening2", EnemyPat_BlockBreak_Sakana },
	{ "Claude41", "ブロック崩しをモチーフにした弾幕", "", "", "Quiet_Opening2", EnemyPat_BlockBreak_Claude },
	{ "Qwen41", "ブロック崩しをモチーフにした弾幕", "", "", "Quiet_Opening2", EnemyPat_BlockBreak_Qwen },
	{ "Kimi41", "ブロック崩しをモチーフにした弾幕", "", "", "Quiet_Opening2", EnemyPat_BlockBreak_Kimi },
	{ "DeepSeek42", "ピラミッドをモチーフにした弾幕", "", "", "Desert_Storm", EnemyPat_Pyramid_DeepSeek },
	{ "ChatGPT42", "ピラミッドをモチーフにした弾幕", "王墓崩壊 ― ピラミッド・カタストロフ", "", "Desert_Storm", EnemyPat_Pyramid_ChatGPT },
	{ "Gemini42", "ピラミッドをモチーフにした弾幕", "ファラオ・コア：黄金の階層構築", "", "Desert_Storm", EnemyPat_Pyramid_Gemini },
	{ "Grok42", "ピラミッドをモチーフにした弾幕", "", "", "Desert_Storm", EnemyPat_Pyramid_Grok },
	{ "Claude42", "ピラミッドをモチーフにした弾幕", "", "", "Desert_Storm", EnemyPat_Pyramid_Claude },
	{ "Qwen42", "ピラミッドをモチーフにした弾幕", "", "", "Desert_Storm", EnemyPat_Pyramid_Qwen },
	{ "Kimi42", "ピラミッドをモチーフにした弾幕", "", "", "Desert_Storm", EnemyPat_Pyramid_Kimi },
	{ "Zai42", "ピラミッドをモチーフにした弾幕", "", "", "Desert_Storm", EnemyPat_Pyramid_Zai },
	{ "DeepSeek43", "ボスが体当たりしてくる弾幕", "", "", "Cathedral_Ashes", EnemyPat_Tackle_DeepSeek },
	{ "ChatGPT43", "ボスが体当たりしてくる弾幕", "獣王突撃・轟雷狩猟陣", "", "Cathedral_Ashes", EnemyPat_Tackle_ChatGPT },
	{ "Gemini43", "ボスが体当たりしてくる弾幕", "", "", "Cathedral_Ashes", EnemyPat_Tackle_Gemini },
	{ "Grok43", "ボスが体当たりしてくる弾幕", "", "", "Cathedral_Ashes", EnemyPat_Tackle_Grok },
	{ "Claude43", "ボスが体当たりしてくる弾幕", "", "", "Cathedral_Ashes", EnemyPat_Tackle_Claude },
	{ "Qwen43", "ボスが体当たりしてくる弾幕", "", "", "Cathedral_Ashes", EnemyPat_Tackle_Qwen },
	{ "Kimi43", "ボスが体当たりしてくる弾幕", "", "", "Cathedral_Ashes", EnemyPat_Tackle_Kimi },
	{ "Zai43", "ボスが体当たりしてくる弾幕", "グラビティ・コメット・レムナント", "", "Cathedral_Ashes", EnemyPat_Tackle_Zai },
	{ "DeepSeek44", "矢印をモチーフにした弾幕", "鏃穿つ方陣", "", "Arrow_Circuit", EnemyPat_Arrow_DeepSeek },
	{ "ChatGPT44", "矢印をモチーフにした弾幕", "矢印機関「アロー・コンベア」", "", "Arrow_Circuit", EnemyPat_Arrow_ChatGPT },
	{ "Gemini44", "矢印をモチーフにした弾幕", "", "", "Arrow_Circuit", EnemyPat_Arrow_Gemini },
	{ "Grok44", "矢印をモチーフにした弾幕", "", "", "Arrow_Circuit", EnemyPat_Arrow_Grok },
	{ "Claude44", "矢印をモチーフにした弾幕", "", "", "Arrow_Circuit", EnemyPat_Arrow_Claude },
	{ "Qwen44", "矢印をモチーフにした弾幕", "", "", "Arrow_Circuit", EnemyPat_Arrow_Qwen },
	{ "Kimi44", "矢印をモチーフにした弾幕", "", "", "Arrow_Circuit", EnemyPat_Arrow_Kimi },
	{ "Zai44", "矢印をモチーフにした弾幕", "ホーミング・イリュージョン", "", "Arrow_Circuit", EnemyPat_Arrow_Zai },
	{ "DeepSeek45", "DNAをモチーフにした弾幕", "", "", "Helix_Test_Tube", EnemyPat_DNA_DeepSeek },
	{ "ChatGPT45", "DNAをモチーフにした弾幕", "螺旋遺伝子「ダブルヘリックス・レプリケーション」", "", "Helix_Test_Tube", EnemyPat_DNA_ChatGPT },
	{ "Gemini45", "DNAをモチーフにした弾幕", "", "", "Helix_Test_Tube", EnemyPat_DNA_Gemini },
	{ "Grok45", "DNAをモチーフにした弾幕", "", "", "Helix_Test_Tube", EnemyPat_DNA_Grok },
	{ "Claude45", "DNAをモチーフにした弾幕", "", "", "Helix_Test_Tube", EnemyPat_DNA_Claude },
	{ "Qwen45", "DNAをモチーフにした弾幕", "", "", "Helix_Test_Tube", EnemyPat_DNA_Qwen },
	{ "Kimi45", "DNAをモチーフにした弾幕", "ヘリカル・ゲノム", "", "Crystalline Rain Circuit", EnemyPat_DNA_Kimi },
	{ "Zai45", "DNAをモチーフにした弾幕", "", "", "Helix_Test_Tube", EnemyPat_DNA_Zai },
	{ "DeepSeek46", "大砂嵐をモチーフにした弾幕", "砂塵旋風『埋没の大砂丘』", "", "Desert Mirage Run", EnemyPat_SandStorm_DeepSeek },
	{ "ChatGPT46", "大砂嵐をモチーフにした弾幕", "砂塵眼・テンペストコア", "", "Neon_Dune_Rush", EnemyPat_SandStorm_ChatGPT },
	{ "Gemini46", "大砂嵐をモチーフにした弾幕", "", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Gemini },
	{ "Grok46", "大砂嵐をモチーフにした弾幕", "", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Grok },
	{ "Claude46", "大砂嵐をモチーフにした弾幕", "", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Claude },
	{ "Qwen46", "大砂嵐をモチーフにした弾幕", "", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Qwen },
	{ "Kimi46", "大砂嵐をモチーフにした弾幕", "", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Kimi },
	{ "Zai46", "大砂嵐をモチーフにした弾幕", "", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Zai },
	{ "DeepSeek47", "へにょりレーザーを用いた弾幕", "蛇腹追詰レーザー “メアンダサーペント”", "", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_DeepSeek },
	{ "ChatGPT47", "へにょりレーザーを用いた弾幕", "蛇の巣（Serpent Nest）", "", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_ChatGPT },
	{ "Gemini47", "へにょりレーザーを用いた弾幕", "へにょりスラローム（曲折迷宮）", "", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Gemini },
	{ "Grok47", "へにょりレーザーを用いた弾幕", "蛇舞繚乱（へびまいりょうらん）", "", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Grok },
	{ "Claude47", "へにょりレーザーを用いた弾幕", "大蛇乱舞(おろちらんぶ)", "", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Claude },
	{ "Qwen47", "へにょりレーザーを用いた弾幕", "", "", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Qwen },
	{ "Kimi47", "へにょりレーザーを用いた弾幕", "螺旋の縫い目（Spiral Seam）", "", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Kimi },
	{ "Zai47", "へにょりレーザーを用いた弾幕", "蠕動交差（ぜんどうこうさ）の檻", "", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Zai },
	{ "DeepSeek48", "潮吹きをモチーフにした弾幕", "天恵の噴泉（ブレス・オブ・セタシア）", "", "Tidal Ascend", EnemyPat_Spout_DeepSeek },
	{ "ChatGPT48", "潮吹きをモチーフにした弾幕", "潮吹き「ブロウ・カラム」", "", "Tidal Ascend", EnemyPat_Spout_ChatGPT },
	{ "Gemini48", "潮吹きをモチーフにした弾幕", "大噴流「アクア・プレッシャー」", "", "Tidal Ascend", EnemyPat_Spout_Gemini },
	{ "Grok48", "潮吹きをモチーフにした弾幕", "激潮噴出（Geki-chou Funshutsu）", "", "Tidal Ascend", EnemyPat_Spout_Grok },
	{ "Claude48", "潮吹きをモチーフにした弾幕", "怒濤潮吹き", "", "Tidal Ascend", EnemyPat_Spout_Claude },
	{ "Qwen48", "潮吹きをモチーフにした弾幕", "", "", "Tidal Ascend", EnemyPat_Spout_Qwen },
	{ "Sakana48", "潮吹きをモチーフにした弾幕", "潮吹き噴流（しおふきふんりゅう）", "", "Tidal Ascend", EnemyPat_Spout_Sakana },
	{ "Zai48", "潮吹きをモチーフにした弾幕", "", "", "Tidal Ascend", EnemyPat_Spout_Zai },
	{ "DeepSeek49", "ライフゲームをモチーフにした弾幕", "コンウェイの産声（グライダーガン変奏）", "", "Digital Grid Run", EnemyPat_LifeGame_DeepSeek },
	{ "ChatGPT49", "ライフゲームをモチーフにした弾幕", "コンウェイ・コロニー", "", "Digital Grid Run", EnemyPat_LifeGame_ChatGPT },
	{ "Gemini49", "ライフゲームをモチーフにした弾幕", "ジェネレーション・グリッド（Generation Grid）", "", "Digital Grid Run", EnemyPat_LifeGame_Gemini },
	{ "Grok49", "ライフゲームをモチーフにした弾幕", "生命の脈動 (Pulsating Life)", "", "Digital Grid Run", EnemyPat_LifeGame_Grok },
	{ "Claude49", "ライフゲームをモチーフにした弾幕", "生々流転", "", "Digital Grid Run", EnemyPat_LifeGame_Claude },
	{ "Qwen49", "ライフゲームをモチーフにした弾幕", "", "", "Digital Grid Run", EnemyPat_LifeGame_Qwen },
	{ "Kimi49", "ライフゲームをモチーフにした弾幕", "世代交代の連鎖（Generational Chain）", "", "Digital Grid Run", EnemyPat_LifeGame_Kimi },
	{ "Zai49", "ライフゲームをモチーフにした弾幕", "細胞律動弾幕 -R-pentomino-", "", "Digital Grid Run", EnemyPat_LifeGame_Zai },
	{ "DeepSeek50", "スイミーをモチーフにした弾幕", "大きな魚の目になるスイミー", "", "Shoal Storm Run", EnemyPat_Swimmy_DeepSeek },
	{ "ChatGPT50", "スイミーをモチーフにした弾幕", "スイミー（群れの目）", "", "Shoal Storm Run", EnemyPat_Swimmy_ChatGPT },
	{ "Gemini50", "スイミーをモチーフにした弾幕", "スイミー・フォーメーション（Swimmy Tactics）", "", "Shoal Storm Run", EnemyPat_Swimmy_Gemini },
	{ "Grok50", "スイミーをモチーフにした弾幕", "スイミーの大群形成（Swimmy's School Formation）", "", "Shoal Storm Run", EnemyPat_Swimmy_Grok },
	{ "Claude50", "スイミーをモチーフにした弾幕", "群魚結像 -スイミー-", "", "Shoal Storm Run", EnemyPat_Swimmy_Claude },
	{ "Qwen50", "スイミーをモチーフにした弾幕", "", "", "Shoal Storm Run", EnemyPat_Swimmy_Qwen },
	{ "Kimi50", "スイミーをモチーフにした弾幕", "スイミーの大魚陣形", "", "Shoal Storm Run", EnemyPat_Swimmy_Kimi },
	{ "Zai50", "スイミーをモチーフにした弾幕", "紅き群れと一匹の墨～巨大魚の遊泳～", "", "Shoal Storm Run", EnemyPat_Swimmy_Zai },
	{ "DeepSeek51", "イライラ棒をモチーフにした弾幕", "電網迷路「フラッシュ・メイズ」", "", "Clockwork Panic Run", EnemyPat_Irairabou_DeepSeek },
	{ "ChatGPT51", "イライラ棒をモチーフにした弾幕", "イライラ迷路", "", "Clockwork Panic Run", EnemyPat_Irairabou_ChatGPT },
	{ "Gemini51", "イライラ棒をモチーフにした弾幕", "電撃精密回廊 ～ イライラ・コリドー", "", "Clockwork Panic Run", EnemyPat_Irairabou_Gemini },
	{ "Grok51", "イライラ棒をモチーフにした弾幕", "イライラ棒・極（きわみ）", "", "Clockwork Panic Run", EnemyPat_Irairabou_Grok },
	{ "Claude51", "イライラ棒をモチーフにした弾幕", "銅線回廊", "", "Clockwork Panic Run", EnemyPat_Irairabou_Claude },
	{ "Qwen51", "イライラ棒をモチーフにした弾幕", "電流迷路『イライラ・コイル』", "", "Clockwork Panic Run", EnemyPat_Irairabou_Qwen },
	{ "Kimi51", "イライラ棒をモチーフにした弾幕", "電壁「ビリビリ回廊」", "", "Clockwork Panic Run", EnemyPat_Irairabou_Kimi },
	{ "Zai51", "イライラ棒をモチーフにした弾幕", "", "", "Clockwork Panic Run", EnemyPat_Irairabou_Zai },
	{ "DeepSeek52", "蜂をモチーフにした弾幕", "蜂の八字舞踏「蜜導の輪舞」", "", "Hive Storm", EnemyPat_Bee_DeepSeek },
	{ "ChatGPT52", "蜂をモチーフにした弾幕", "ハニカム・スウォーム（Honeycomb Swarm）", "", "Hive Storm", EnemyPat_Bee_ChatGPT },
	{ "Gemini52", "蜂をモチーフにした弾幕", "ハニカム・プリズン ＆ デス・ニードル（蜜蜂の檻と死の針）", "", "Hive Storm", EnemyPat_Bee_Gemini },
	{ "Grok52", "蜂をモチーフにした弾幕", "蜂の巣攻勢 - Honeycomb Swarm", "", "Hive Storm", EnemyPat_Bee_Grok },
	{ "Claude52", "蜂をモチーフにした弾幕", "羽音の八の字舞", "", "Hive Storm", EnemyPat_Bee_Claude },
	{ "Qwen52", "蜂をモチーフにした弾幕", "", "", "Hive Storm", EnemyPat_Bee_Qwen },
	{ "Kimi52", "蜂をモチーフにした弾幕", "蜜蝋六重奏（ハニカム・セクテット）", "", "Hive Storm", EnemyPat_Bee_Kimi },
	{ "Zai52", "蜂をモチーフにした弾幕", "六角の檻と狂気の羽音", "", "Hive Storm", EnemyPat_Bee_Zai },
	{ "DeepSeek53", "大文字をモチーフにした弾幕", "鋭角の審判「エイペックス・ジャッジメント」", "", "Taiko Skyline Run", EnemyPat_Daimonji_DeepSeek },
	{ "ChatGPT53", "大文字をモチーフにした弾幕", "SHIFT FALL（大文字の雨）", "", "Taiko Skyline Run", EnemyPat_Daimonji_ChatGPT },
	{ "Gemini53", "大文字をモチーフにした弾幕", "焔符「大文字送り火 -篝火の檻-」", "", "Taiko Skyline Run", EnemyPat_Daimonji_Gemini },
	{ "Grok53", "大文字をモチーフにした弾幕", "Capital A - Descent Frame", "", "Taiko Skyline Run", EnemyPat_Daimonji_Grok },
	{ "Claude53", "大文字をモチーフにした弾幕", "大文字送り火", "", "Taiko Skyline Run", EnemyPat_Daimonji_Claude },
	{ "Qwen53", "大文字をモチーフにした弾幕", "", "", "Taiko Skyline Run", EnemyPat_Daimonji_Qwen },
	{ "Kimi53", "大文字をモチーフにした弾幕", "Absolute Apex", "", "Taiko Skyline Run", EnemyPat_Daimonji_Kimi },
	{ "Zai53", "大文字をモチーフにした弾幕", "「Z」字斬撃弾幕", "", "Taiko Skyline Run", EnemyPat_Daimonji_Zai },
	{ "DeepSeek54", "ビールかけをモチーフにした弾幕", "祝勝の泡濁流", "", "Tipsy Brass Parade", EnemyPat_BeerSpray_DeepSeek },
	{ "ChatGPT54", "ビールかけをモチーフにした弾幕", "ビールかけ", "", "Tipsy Brass Parade", EnemyPat_BeerSpray_ChatGPT },
	{ "Gemini54", "ビールかけをモチーフにした弾幕", "歓喜のビア・シャワー（Cheers! Burst）", "", "Tipsy Brass Parade", EnemyPat_BeerSpray_Gemini },
	{ "Grok54", "ビールかけをモチーフにした弾幕", "無限ビールかけ祭り（Endless Beer Shower）", "", "Tipsy Brass Parade", EnemyPat_BeerSpray_Grok },
	{ "Claude54", "ビールかけをモチーフにした弾幕", "祝勝ビールかけ", "", "Tipsy Brass Parade", EnemyPat_BeerSpray_Claude },
	{ "Qwen54", "ビールかけをモチーフにした弾幕", "", "", "Tipsy Brass Parade", EnemyPat_BeerSpray_Qwen },
	{ "Kimi54", "ビールかけをモチーフにした弾幕", "泡沫の宴（エビュリエンス・フェスト）", "", "Tipsy Brass Parade", EnemyPat_BeerSpray_Kimi },
	{ "Zai54", "ビールかけをモチーフにした弾幕", "溢れる狂乱の飛沫（エクスプロージング・ビアスプラッシュ）", "", "Tipsy Brass Parade", EnemyPat_BeerSpray_Zai },
	{ "DeepSeek55", "サムネ映えする弾幕", "時空の歪曲円舞《クロノス・スパイラル》", "", "Astral Blade Run", EnemyPat_ThumbnailFriendly_DeepSeek },
	{ "ChatGPT55", "サムネ映えする弾幕", "ガラス細工の万華鏡", "", "Astral Blade Run", EnemyPat_ThumbnailFriendly_ChatGPT },
	{ "Gemini55", "サムネ映えする弾幕", "カレイド・フェニックス（万華鏡の不死鳥）", "", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Gemini },
	{ "Grok55", "サムネ映えする弾幕", "極彩螺旋華", "", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Grok },
	{ "Claude55", "サムネ映えする弾幕", "孔雀絢爛", "", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Claude },
	{ "Qwen55", "サムネ映えする弾幕", "星喰うネオン蓮の絶頂", "", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Qwen },
	{ "Kimi55", "サムネ映えする弾幕", "螺旋の花園", "", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Kimi },
	{ "Zai55", "サムネ映えする弾幕", "彩華「極彩の万華鏡」", "", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Zai },
	{ "DeepSeek56", "エビングハウス錯視をモチーフにした弾幕", "錯視牢獄 - Ebbinghaus Cage -", "", "Locrian Barrage", EnemyPat_Ebbinghaus_DeepSeek },
	{ "ChatGPT56", "エビングハウス錯視をモチーフにした弾幕", "エビングハウス・イリュージョン", "", "Locrian Barrage", EnemyPat_Ebbinghaus_ChatGPT },
	{ "Gemini56", "エビングハウス錯視をモチーフにした弾幕", "錯視『相対的中心核』", "", "Locrian Barrage", EnemyPat_Ebbinghaus_Gemini },
	{ "Grok56", "エビングハウス錯視をモチーフにした弾幕", "エビングハウス・イリュージョンリング", "", "Locrian Barrage", EnemyPat_Ebbinghaus_Grok },
	{ "Claude56", "エビングハウス錯視をモチーフにした弾幕", "衆星拱月", "", "Locrian Barrage", EnemyPat_Ebbinghaus_Claude },
	{ "Qwen56", "エビングハウス錯視をモチーフにした弾幕", "錯弾「エビングハウスの庭」", "", "Locrian Barrage", EnemyPat_Ebbinghaus_Qwen },
	{ "Kimi56", "エビングハウス錯視をモチーフにした弾幕", "相対視の欺罔", "", "Locrian Barrage", EnemyPat_Ebbinghaus_Kimi },
	{ "Zai56", "エビングハウス錯視をモチーフにした弾幕", "欺瞞の円環", "", "Locrian Barrage", EnemyPat_Ebbinghaus_Zai },
	{ "DeepSeek57", "ルール30をモチーフにした弾幕", "ルール30の降下波動", "", "Bullet Hell Cascade", EnemyPat_Rule30_DeepSeek },
	{ "ChatGPT57", "ルール30をモチーフにした弾幕", "ルール30・カオスフロント", "", "Bullet Hell Cascade", EnemyPat_Rule30_ChatGPT },
	{ "Gemini57", "ルール30をモチーフにした弾幕", "カオスと秩序のセル・カスケード", "", "Bullet Hell Cascade", EnemyPat_Rule30_Gemini },
	{ "Grok57", "ルール30をモチーフにした弾幕", "ルール30カスケード", "", "Bullet Hell Cascade", EnemyPat_Rule30_Grok },
	{ "Claude57", "ルール30をモチーフにした弾幕", "一粒万倍", "", "Bullet Hell Cascade", EnemyPat_Rule30_Claude },
	{ "Qwen57", "ルール30をモチーフにした弾幕", "ルール30：フラクタル・カスケード", "", "Bullet Hell Cascade", EnemyPat_Rule30_Qwen },
	{ "Kimi57", "ルール30をモチーフにした弾幕", "非対称三角陣 ～Rule30～", "", "Bullet Hell Cascade", EnemyPat_Rule30_Kimi },
	{ "Zai57", "ルール30をモチーフにした弾幕", "ルール30：非対称拡散弾幕", "", "Bullet Hell Cascade", EnemyPat_Rule30_Zai },
	{ "DeepSeek58", "アリジゴクをモチーフにした弾幕", "底なし蟻地獄", "", "Desert Mirage Run", EnemyPat_Antlion_DeepSeek },
	{ "ChatGPT58", "アリジゴクをモチーフにした弾幕", "蟻地獄", "", "Desert Mirage Run", EnemyPat_Antlion_ChatGPT },
	{ "Gemini58", "アリジゴクをモチーフにした弾幕", "流砂の地獄陣（アントリオン・トラップ）", "", "Desert Mirage Run", EnemyPat_Antlion_Gemini },
	{ "Grok58", "アリジゴクをモチーフにした弾幕", "砂坑の顎", "", "Desert Mirage Run", EnemyPat_Antlion_Grok },
	{ "Claude58", "アリジゴクをモチーフにした弾幕", "蟻地獄陥穽", "", "Desert Mirage Run", EnemyPat_Antlion_Claude },
	{ "Qwen58", "アリジゴクをモチーフにした弾幕", "砂漠の落とし穴 アントライオンの罠", "", "Desert Mirage Run", EnemyPat_Antlion_Qwen },
	{ "Kimi58", "アリジゴクをモチーフにした弾幕", "漏斗陥穽（ろうとかんせい）－ Antlion Funnel", "", "Desert Mirage Run", EnemyPat_Antlion_Kimi },
	{ "Zai58", "アリジゴクをモチーフにした弾幕", "帰路なき砂蟲の捕食円", "", "Desert Mirage Run", EnemyPat_Antlion_Zai },
	{ "DeepSeek59", "三三七拍子のリズムで弾を撃つ弾幕", "祝砲乱舞「三三七拍子」", "", "Matsuri Bullet Run", EnemyPat_337Beat_DeepSeek },
	{ "ChatGPT59", "三三七拍子のリズムで弾を撃つ弾幕", "三三七拍子連射", "", "Matsuri Bullet Run", EnemyPat_337Beat_ChatGPT },
	{ "Gemini59", "三三七拍子のリズムで弾を撃つ弾幕", "祝砲・演舞三三七拍子", "", "Matsuri Bullet Run", EnemyPat_337Beat_Gemini },
	{ "Grok59", "三三七拍子のリズムで弾を撃つ弾幕", "祝い撃ち", "", "Matsuri Bullet Run", EnemyPat_337Beat_Grok },
	{ "Claude59", "三三七拍子のリズムで弾を撃つ弾幕", "三三七拍子 ―― 応援団風連続撃ち", "", "Matsuri Bullet Run", EnemyPat_337Beat_Claude },
	{ "Qwen59", "三三七拍子のリズムで弾を撃つ弾幕", "神輿乱舞・三三七拍子", "", "Matsuri Bullet Run", EnemyPat_337Beat_Qwen },
	{ "Kimi59", "三三七拍子のリズムで弾を撃つ弾幕", "三三七の舞（さんさんななのまい）", "", "Matsuri Bullet Run", EnemyPat_337Beat_Kimi },
	{ "Zai59", "三三七拍子のリズムで弾を撃つ弾幕", "祭囃子・三三七の陣", "", "Matsuri Bullet Run", EnemyPat_337Beat_Zai },
	{ "DeepSeek60", "ボスが撃ち返してくる弾幕", "散華の呪詛針（さんげのじゅそばり）", "", "Fractal Gamelan Rush", EnemyPat_Counter_DeepSeek },
	{ "ChatGPT60", "ボスが撃ち返してくる弾幕", "報復の反響波", "", "Fractal Gamelan Rush", EnemyPat_Counter_ChatGPT },
	{ "Gemini60", "ボスが撃ち返してくる弾幕", "波紋共鳴（リップル・カウンター）", "", "Fractal Gamelan Rush", EnemyPat_Counter_Gemini },
	{ "Grok60", "ボスが撃ち返してくる弾幕", "傷の残響", "", "Fractal Gamelan Rush", EnemyPat_Counter_Grok },
	{ "Claude60", "ボスが撃ち返してくる弾幕", "鏡面反撃「破鏡乱反射」", "", "Fractal Gamelan Rush", EnemyPat_Counter_Claude },
	{ "Qwen60", "ボスが撃ち返してくる弾幕", "砕け散る紅硝子（クリムゾン・フラグメント）", "", "Fractal Gamelan Rush", EnemyPat_Counter_Qwen },
	{ "Kimi60", "ボスが撃ち返してくる弾幕", "血の代償（Blood Tithe）", "", "Fractal Gamelan Rush", EnemyPat_Counter_Kimi },
	{ "Zai60", "ボスが撃ち返してくる弾幕", "瞬停分裂弾", "", "Fractal Gamelan Rush", EnemyPat_Counter_Zai },
	{ "DeepSeek61", "正十二面体をモチーフにした弾幕", "ドデカヘドラル・ケージ", "", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_DeepSeek },
	{ "ChatGPT61", "正十二面体をモチーフにした弾幕", "十二面体結界", "", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_ChatGPT },
	{ "Gemini61", "正十二面体をモチーフにした弾幕", "黄金正多面体陣 -Dodecahedron-", "", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Gemini },
	{ "Grok61", "正十二面体をモチーフにした弾幕", "黄金立体の檻", "", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Grok },
	{ "Claude61", "正十二面体をモチーフにした弾幕", "正十二面体・展開陣", "", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Claude },
	{ "Qwen61", "正十二面体をモチーフにした弾幕", "幾何『正十二面体の鏡像』", "", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Qwen },
	{ "Kimi61", "正十二面体をモチーフにした弾幕", "五重奏の十二審判", "", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Kimi },
	{ "Zai61", "正十二面体をモチーフにした弾幕", "正十二面陣・虚数結界", "", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Zai },
	{ "DeepSeek62", "カオスすぎる弾幕", "超次元崩壊輪廻（ハイパーカオス・サムサーラ）", "", "Bullet Hell Finale", EnemyPat_TooChaotic_DeepSeek },
	{ "ChatGPT62", "カオスすぎる弾幕", "乱流回廊「スパイラル・スクランブル」", "", "Bullet Hell Finale", EnemyPat_TooChaotic_ChatGPT },
	{ "Gemini62", "カオスすぎる弾幕", "確定性混沌（デターミニスティック・カオス）", "", "Bullet Hell Finale", EnemyPat_TooChaotic_Gemini },
	{ "Grok62", "カオスすぎる弾幕", "虚数螺旋崩壊", "", "Bullet Hell Finale", EnemyPat_TooChaotic_Grok },
	{ "Claude62", "カオスすぎる弾幕", "狂乱万華鏡", "", "Bullet Hell Finale", EnemyPat_TooChaotic_Claude },
	{ "Qwen62", "カオスすぎる弾幕", "次元崩壊の万華鏡", "", "Bullet Hell Finale", EnemyPat_TooChaotic_Qwen },
	{ "Kimi62", "カオスすぎる弾幕", "侵食多重螺旋「アポカリプティック・ネスト」", "", "Bullet Hell Finale", EnemyPat_TooChaotic_Kimi },
	{ "Zai62", "カオスすぎる弾幕", "過負荷グリッチ・カスケード", "", "Bullet Hell Finale", EnemyPat_TooChaotic_Zai },
	{ "DeepSeek63", "サインポールをモチーフにした弾幕", "バーバーズ・ポール", "", "Lochfire Arpeggio", EnemyPat_SignPole_DeepSeek },
	{ "ChatGPT63", "サインポールをモチーフにした弾幕", "サインポール・スパイラル", "", "Lochfire Arpeggio", EnemyPat_SignPole_ChatGPT },
	{ "Gemini63", "サインポールをモチーフにした弾幕", "トリコロール・ヘリックス", "", "Lochfire Arpeggio", EnemyPat_SignPole_Gemini },
	{ "Grok63", "サインポールをモチーフにした弾幕", "サインポール螺旋", "", "Lochfire Arpeggio", EnemyPat_SignPole_Grok },
	{ "Claude63", "サインポールをモチーフにした弾幕", "三色回転塔", "", "Lochfire Arpeggio", EnemyPat_SignPole_Claude },
	{ "Qwen63", "サインポールをモチーフにした弾幕", "錯覚のサインポール・ラビリンス", "", "Lochfire Arpeggio", EnemyPat_SignPole_Qwen },
	{ "Kimi63", "サインポールをモチーフにした弾幕", "交差点標識 － Crossroad Signpost", "", "Lochfire Arpeggio", EnemyPat_SignPole_Kimi },
	{ "Zai63", "サインポールをモチーフにした弾幕", "カントリーサイン・フォール", "", "Lochfire Arpeggio", EnemyPat_SignPole_Zai },
	{ "DeepSeek64", "三色団子をモチーフにした弾幕", "三色団子・串輪舞", "", "Moonlit Danmaku Run", EnemyPat_TricolorDango_DeepSeek },
	{ "ChatGPT64", "三色団子をモチーフにした弾幕", "三色団子スパイラル", "", "Moonlit Danmaku Run", EnemyPat_TricolorDango_ChatGPT },
	{ "Gemini64", "三色団子をモチーフにした弾幕", "春風・三色串崩し", "", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Gemini },
	{ "Grok64", "三色団子をモチーフにした弾幕", "三色串刺し弾幕", "", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Grok },
	{ "Claude64", "三色団子をモチーフにした弾幕", "三色串舞", "", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Claude },
	{ "Qwen64", "三色団子をモチーフにした弾幕", "花見の宴・三色だんごの串刺し", "", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Qwen },
	{ "Kimi64", "三色団子をモチーフにした弾幕", "花見団子の輪舞曲", "", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Kimi },
	{ "Zai64", "三色団子をモチーフにした弾幕", "彩り三色・団子の逆転螺旋", "", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Zai },
	{ "DeepSeek65", "ヒュドラをモチーフにした弾幕", "不死結界「生首の庭」", "", "Nine Heads Rebirth", EnemyPat_Hydra_DeepSeek },
	{ "ChatGPT65", "ヒュドラをモチーフにした弾幕", "", "", "Nine Heads Rebirth", EnemyPat_Hydra_ChatGPT },
	{ "Gemini65", "ヒュドラをモチーフにした弾幕", "不滅の九頭連鎖（ハイドラ・リジェネシス）", "", "Nine Heads Rebirth", EnemyPat_Hydra_Gemini },
	{ "Grok65", "ヒュドラをモチーフにした弾幕", "多頭再生弾幕", "", "Nine Heads Rebirth", EnemyPat_Hydra_Grok },
	{ "Claude65", "ヒュドラをモチーフにした弾幕", "双首再生", "", "Nine Heads Rebirth", EnemyPat_Hydra_Claude },
	{ "Qwen65", "ヒュドラをモチーフにした弾幕", "蛇再生「ヒュドラ・リジェネレイト」", "", "Nine Heads Rebirth", EnemyPat_Hydra_Qwen },
	{ "Kimi65", "ヒュドラをモチーフにした弾幕", "断罪の輪廻 ― proliferating heads", "", "Nine Heads Rebirth", EnemyPat_Hydra_Kimi },
	{ "Zai65", "ヒュドラをモチーフにした弾幕", "毒蛇の徘徊する吐息", "", "Nine Heads Rebirth", EnemyPat_Hydra_Zai },
	{ "DeepSeek66", "超巨大弾を使った弾幕", "超巨大環状弾「縮檻 －シュクコウ－」", "", "Leviathan Shell", EnemyPat_HugeBullet_DeepSeek },
	{ "ChatGPT66", "超巨大弾を使った弾幕", "重力核「グラビティ・コア」", "", "Leviathan Shell", EnemyPat_HugeBullet_ChatGPT },
	{ "Gemini66", "超巨大弾を使った弾幕", "グラビティ・コアと破砕衝撃波", "", "Leviathan Shell", EnemyPat_HugeBullet_Gemini },
	{ "Grok66", "超巨大弾を使った弾幕", "巨弾の呼吸・潮汐弾幕", "", "Leviathan Shell", EnemyPat_HugeBullet_Grok },
	{ "Claude66", "超巨大弾を使った弾幕", "大玉転がし", "", "Leviathan Shell", EnemyPat_HugeBullet_Claude },
	{ "Qwen66", "超巨大弾を使った弾幕", "超巨大弾「ムーンフォール・カーテン」", "", "Leviathan Shell", EnemyPat_HugeBullet_Qwen },
	{ "Kimi66", "超巨大弾を使った弾幕", "重力の瞳（グラヴィティ・アイズ）", "", "Leviathan Shell", EnemyPat_HugeBullet_Kimi },
	{ "Zai66", "超巨大弾を使った弾幕", "崩星の重核", "", "Leviathan Shell", EnemyPat_HugeBullet_Zai },
	{ "DeepSeek67", "世界一難しい弾幕", "因果遡行『不可逆の残影』", "", "Cyber Doom Circuit", EnemyPat_TheHardest_DeepSeek },
	{ "ChatGPT67", "世界一難しい弾幕", "カオス・イベントホライズン", "", "Cyber Doom Circuit", EnemyPat_TheHardest_ChatGPT },
	{ "Gemini67", "世界一難しい弾幕", "量子位相干渉：事象の地平線", "", "Cyber Doom Circuit", EnemyPat_TheHardest_Gemini },
	{ "Grok67", "世界一難しい弾幕", "無限螺旋・時間歪曲弾幕", "", "Cyber Doom Circuit", EnemyPat_TheHardest_Grok },
	{ "Claude67", "世界一難しい弾幕", "終末刻鐘", "", "Cyber Doom Circuit", EnemyPat_TheHardest_Claude },
	{ "Qwen67", "世界一難しい弾幕", "未来確定弾幕「ラプラスの最終定理」", "", "Cyber Doom Circuit", EnemyPat_TheHardest_Qwen },
	{ "Kimi67", "世界一難しい弾幕", "無限分岐のカオス・フラクタル", "", "Cyber Doom Circuit", EnemyPat_TheHardest_Kimi },
	{ "Zai67", "世界一難しい弾幕", "虚数迷宮・因果律の崩壊", "", "Cyber Doom Circuit", EnemyPat_TheHardest_Zai },
	{ "DeepSeek68", "花火をモチーフにした弾幕", "大輪牡丹花火・千輪咲き", "", "Starburst Matsuri", EnemyPat_Firework_DeepSeek },
	{ "ChatGPT68", "花火をモチーフにした弾幕", "残光花火", "", "Starburst Matsuri", EnemyPat_Firework_ChatGPT },
	{ "Gemini68", "花火をモチーフにした弾幕", "昇り曲導付 尺玉千輪菊", "", "Starburst Matsuri", EnemyPat_Firework_Gemini },
	{ "Grok68", "花火をモチーフにした弾幕", "菊花大輪", "", "Starburst Matsuri", EnemyPat_Firework_Grok },
	{ "Claude68", "花火をモチーフにした弾幕", "尺玉二段咲き", "", "Starburst Matsuri", EnemyPat_Firework_Claude },
	{ "Qwen68", "花火をモチーフにした弾幕", "花火「三尺玉・三段咲き」", "", "Starburst Matsuri", EnemyPat_Firework_Qwen },
	{ "Kimi68", "花火をモチーフにした弾幕", "昇華の瞬間（アセンション・ブルーム）", "", "Starburst Matsuri", EnemyPat_Firework_Kimi },
	{ "Zai68", "花火をモチーフにした弾幕", "二重咲き・昇華スターマイン", "", "Starburst Matsuri", EnemyPat_Firework_Zai },
	{ "DeepSeek69", "スイカゲームをモチーフにした弾幕", "果実合成「弾けるスイカ連鎖」", "", "Watermelon Sky Run", EnemyPat_SuikaGame_DeepSeek },
	{ "ChatGPT69", "スイカゲームをモチーフにした弾幕", "果実融合「スイカ連鎖フィーバー」", "", "Watermelon Sky Run", EnemyPat_SuikaGame_ChatGPT },
	{ "Gemini69", "スイカゲームをモチーフにした弾幕", "シンカの連鎖弾（くだものフュージョン）", "", "Watermelon Sky Run", EnemyPat_SuikaGame_Gemini },
	{ "Grok69", "スイカゲームをモチーフにした弾幕", "果実融合弾幕", "", "Watermelon Sky Run", EnemyPat_SuikaGame_Grok },
	{ "Claude69", "スイカゲームをモチーフにした弾幕", "果実転生", "", "Watermelon Sky Run", EnemyPat_SuikaGame_Claude },
	{ "Qwen69", "スイカゲームをモチーフにした弾幕", "果実合成のスイカ割り", "", "Watermelon Sky Run", EnemyPat_SuikaGame_Qwen },
	{ "Kimi69", "スイカゲームをモチーフにした弾幕", "進化の果実列", "", "Watermelon Sky Run", EnemyPat_SuikaGame_Kimi },
	{ "Zai69", "スイカゲームをモチーフにした弾幕", "重力合成弾幕・果実のカスケード", "", "Watermelon Sky Run", EnemyPat_SuikaGame_Zai },
	{ "DeepSeek70", "クラドニ図形をモチーフにした弾幕", "響板「クラドニの砂紋（さもん）」", "", "Chladni Pulse", EnemyPat_Chladni_DeepSeek },
	{ "ChatGPT70", "クラドニ図形をモチーフにした弾幕", "響界クラドニ", "", "Chladni Pulse", EnemyPat_Chladni_ChatGPT },
	{ "Gemini70", "クラドニ図形をモチーフにした弾幕", "共鳴幾何：音叉の檻（Resonant Chladni Cell）", "", "Chladni Pulse", EnemyPat_Chladni_Gemini },
	{ "Grok70", "クラドニ図形をモチーフにした弾幕", "振動節線", "", "Chladni Pulse", EnemyPat_Chladni_Grok },
	{ "Claude70", "クラドニ図形をモチーフにした弾幕", "共振砂紋", "", "Chladni Pulse", EnemyPat_Chladni_Claude },
	{ "Qwen70", "クラドニ図形をモチーフにした弾幕", "共振板『クラドニ・ノードライン』", "", "Chladni Pulse", EnemyPat_Chladni_Qwen },
	{ "Kimi70", "クラドニ図形をモチーフにした弾幕", "砂紋の律動（Chladni Resonance）", "", "Chladni Pulse", EnemyPat_Chladni_Kimi },
	{ "Zai70", "クラドニ図形をモチーフにした弾幕", "交差振動・クラドニの魔方陣", "", "Chladni Pulse", EnemyPat_Chladni_Zai },
	{ "DeepSeek71", "切れかけの電球をモチーフにした弾幕", "終焉のフィラメント", "", "Filament Blackout", EnemyPat_FlickeringLight_DeepSeek },
	{ "ChatGPT71", "切れかけの電球をモチーフにした弾幕", "フィラメント・ラストスタンド", "", "Filament Blackout", EnemyPat_FlickeringLight_ChatGPT },
	{ "Gemini71", "切れかけの電球をモチーフにした弾幕", "終末フィラメント：ラストフラッシュ", "", "Filament Blackout", EnemyPat_FlickeringLight_Gemini },
	{ "Grok71", "切れかけの電球をモチーフにした弾幕", "切れかけフィラメント", "", "Filament Blackout", EnemyPat_FlickeringLight_Grok },
	{ "Claude71", "切れかけの電球をモチーフにした弾幕", "白熱灯断末魔", "", "Filament Blackout", EnemyPat_FlickeringLight_Claude },
	{ "Qwen71", "切れかけの電球をモチーフにした弾幕", "フィラメント・フリッカー", "", "Filament Blackout", EnemyPat_FlickeringLight_Qwen },
	{ "Kimi71", "切れかけの電球をモチーフにした弾幕", "明滅回廊（フリッカー・コリドー）", "", "Filament Blackout", EnemyPat_FlickeringLight_Kimi },
	{ "Zai71", "切れかけの電球をモチーフにした弾幕", "切れかけの白熱灯「断末魔のチカチカ」", "", "Filament Blackout", EnemyPat_FlickeringLight_Zai },
	{ "DeepSeek72", "エターナルフォースブリザードをモチーフにした弾幕", "絶対零度の墓碑銘（フローズン・エピタフ）", "", "Absolute Zero Blizzard", EnemyPat_EternalForceBlizzard_DeepSeek },
	{ "ChatGPT72", "エターナルフォースブリザードをモチーフにした弾幕", "永遠凍結「エターナルフォースブリザード」", "", "Absolute Zero Blizzard", EnemyPat_EternalForceBlizzard_ChatGPT },
	{ "Gemini72", "エターナルフォースブリザードをモチーフにした弾幕", "氷符「絶対零度世界（エターナルフォースブリザード）」", "", "Absolute Zero Blizzard", EnemyPat_EternalForceBlizzard_Gemini },
	{ "Grok72", "エターナルフォースブリザードをモチーフにした弾幕", "氷符「エターナル・フォース・ブリザード」", "", "Absolute Zero Blizzard", EnemyPat_EternalForceBlizzard_Grok },
	{ "Claude72", "エターナルフォースブリザードをモチーフにした弾幕", "絶対氷結宣言 ～エターナルフォースブリザード～", "", "Absolute Zero Blizzard", EnemyPat_EternalForceBlizzard_Claude },
	{ "Qwen72", "エターナルフォースブリザードをモチーフにした弾幕", "氷獄嵐「エターナルフォースブリザード」", "", "Absolute Zero Blizzard", EnemyPat_EternalForceBlizzard_Qwen },
	{ "Kimi72", "エターナルフォースブリザードをモチーフにした弾幕", "絶対零度の螺旋牢獄（Absolute Zero Spiral Prison）", "", "Absolute Zero Blizzard", EnemyPat_EternalForceBlizzard_Kimi },
	{ "Zai72", "エターナルフォースブリザードをモチーフにした弾幕", "永劫吹雪・無限結晶陣", "", "Absolute Zero Blizzard", EnemyPat_EternalForceBlizzard_Zai },
	{ "DeepSeek73", "ボスが瞬間移動する弾幕", "瞬間移動連鎖弾幕「虚空乱舞（こくうらんぶ）」", "", "Quantum Warp Dash", EnemyPat_Warp_DeepSeek },
	{ "ChatGPT73", "ボスが瞬間移動する弾幕", "残像転位", "", "Quantum Warp Dash", EnemyPat_Warp_ChatGPT },
	{ "Gemini73", "ボスが瞬間移動する弾幕", "残影収束陣（アフターイメージ・コンバージェンス）", "", "Quantum Warp Dash", EnemyPat_Warp_Gemini },
	{ "Grok73", "ボスが瞬間移動する弾幕", "影渡り・裂空の輪", "", "Quantum Warp Dash", EnemyPat_Warp_Grok },
	{ "Claude73", "ボスが瞬間移動する弾幕", "残光跳躍陣", "", "Quantum Warp Dash", EnemyPat_Warp_Claude },
	{ "Qwen73", "ボスが瞬間移動する弾幕", "残像ワープ・クロスファイア", "", "Quantum Warp Dash", EnemyPat_Warp_Qwen },
	{ "Kimi73", "ボスが瞬間移動する弾幕", "残響の鏡陣", "", "Quantum Warp Dash", EnemyPat_Warp_Kimi },
	{ "Zai73", "ボスが瞬間移動する弾幕", "座標接続弾幕「シャドウ・リンク」", "", "Quantum Warp Dash", EnemyPat_Warp_Zai },
	{ "DeepSeek74", "たらこスパゲッティをモチーフにした弾幕", "明太子の大渦巻き ～お皿の上のタラコスパゲッティ～", "", "Tarako Fork Panic", EnemyPat_TarakoSpaghetti_DeepSeek },
	{ "ChatGPT74", "たらこスパゲッティをモチーフにした弾幕", "たらこスパゲッティ", "", "Tarako Fork Panic", EnemyPat_TarakoSpaghetti_ChatGPT },
	{ "Gemini74", "たらこスパゲッティをモチーフにした弾幕", "プルチーノ・アルデンテ（明太子スパゲッティの狂気）", "", "Tarako Fork Panic", EnemyPat_TarakoSpaghetti_Gemini },
	{ "Grok74", "たらこスパゲッティをモチーフにした弾幕", "たらこ絡みスパゲッティ", "", "Tarako Fork Panic", EnemyPat_TarakoSpaghetti_Grok },
	{ "Claude74", "たらこスパゲッティをモチーフにした弾幕", "明太絡繰り", "", "Tarako Fork Panic", EnemyPat_TarakoSpaghetti_Claude },
	{ "Qwen74", "たらこスパゲッティをモチーフにした弾幕", "たらこスパゲッティ・アルデンテ", "", "Tarako Fork Panic", EnemyPat_TarakoSpaghetti_Qwen },
	{ "Kimi74", "たらこスパゲッティをモチーフにした弾幕", "たらこクリームの大盛りスパゲッティ", "", "Tarako Fork Panic", EnemyPat_TarakoSpaghetti_Kimi },
	{ "Zai74", "たらこスパゲッティをモチーフにした弾幕", "タラコの爆裂と絡み合う極細麺", "", "Tarako Fork Panic", EnemyPat_TarakoSpaghetti_Zai },
	{ "DeepSeek75", "五芒星をモチーフにした弾幕", "星鎖円舞（せいさえんぶ）", "画面中央に五芒星を形作る小さな弾のラインが展開し、回転しながらゆっくりと拡大する。五芒星の五つの頂点からは自機を狙う弾が定期的に放たれ、ボス本体は左右に動きつつ高速レーザーを発射する。星が最大サイズに達すると急激に収縮し、中心から放射状に破裂弾が飛び散る。その後、再び星が形成されて拡大と破裂を繰り返す、幾何学的でリズミカルな弾幕。", "Pentagram Burst", EnemyPat_Pentagram_DeepSeek },
	{ "ChatGPT75", "五芒星をモチーフにした弾幕", "星喰む五芒星", "回転する巨大な五芒星の輪郭を弾列で描きながら、星の頂点から中央へ向かう放射弾と、中央から外へ広がる5方向弾を時間差で発生させます。回転方向も途中で反転し、星の内側の安全地帯が刻々と変化します。", "Pentagram Burst", EnemyPat_Pentagram_ChatGPT },
	{ "Gemini75", "五芒星をモチーフにした弾幕", "ペンタグラム・レゾナンス（五芒の共鳴）", "ボスを中心に巨大な五芒星を描画・配置した後、その線上から垂直方向へ針弾が一斉に崩壊・拡散し、さらに5つの頂点から回転全方位弾を連射する弾幕。五芒星の描画による安全地帯への瞬間的な退避判断と、崩壊して押し寄せる弾の隙間をくぐる精密な弾抜けアクションを強いる。", "Pentagram Burst", EnemyPat_Pentagram_Gemini },
	{ "Grok75", "五芒星をモチーフにした弾幕", "星辰の呪縛", "ボスを中心に五芒星を形成し、頂点と辺を弾で構成してゆっくり回転させる。辺上の弾は往復移動し、各頂点からプレイヤー方向へ扇状弾を放つ。終盤で回転を加速させた後、辺の弾を放射状に弾き飛ばし、頂点から二次的な小さな五芒星弾を生成して拡散させる。", "Pentagram Burst", EnemyPat_Pentagram_Grok },
	{ "Claude75", "五芒星をモチーフにした弾幕", "五芒星顕現", "五芒星は一筆書き(0→2→4→1→3→0)で描ける図形であることを利用し、筆先が軌跡をなぞりながら弾で星の輪郭を描き上げるところから始まる。完成後は外周の星と、黄金比の内接五角形が互いに逆回転しながら常駐し、外周の5頂点が順番に自機狙い3wayを放つ。続いて星の対角線に沿ってレーザー片が波ごとに向きを反転させながら流れ、伸縮するような呼吸を表現する。最後に予告を挟み、それまでの星形弾すべてがその場から放射状に加速しながら崩壊放散し、中心から自機狙い5wayとリングバーストが放たれて締めくくる。", "Pentagram Burst", EnemyPat_Pentagram_Claude },
	{ "Qwen75", "五芒星をモチーフにした弾幕", "星符「五芒星牢（ペンタグラム・プリズン）」", "ボスを中心に五芒星の結界を形成し、星の辺に沿って弾を流して光る壁を作り出す。さらに頂点からはプレイヤーへの狙い撃ち、中心からは五角形の螺旋弾を発生させ、回転する星の線と内側の渦、外側からの狙い撃ちによる複合的な回避行動を要求する弾幕。", "Pentagram Burst", EnemyPat_Pentagram_Qwen },
	{ "Kimi75", "五芒星をモチーフにした弾幕", "星降りの儀式（Pentagram Invocation）", "ボスを中心に大・中・小の3重五芒星を一筆書きの稜線で描き、各稜線上に弾を配置する。星が完成すると稜線弾が中心に向かって加速し収束した後、中心から五芒星の頂点方向に弾を引き寄せた星型拡散弾を40発放射する。最後に残存した稜線弾が稜線に垂直な方向へ外側に飛散し、安全地帯を奪う。予告・描画・活性化・拡散・崩壊の5段階で儀式感を演出する。", "Pentagram Burst", EnemyPat_Pentagram_Kimi },
	{ "Zai75", "五芒星をモチーフにした弾幕", "五芒星の刻印", "一筆書きの順に頂点を結ぶように赤い大玉を発射し、画面上に五芒星の線を描きます。大玉が線の交差点を通過した瞬間に青い中玉を扇状に炸裂させ、これを少し回転させながら連続して展開することで、美しい星形の軌跡とリズミカルな炸裂が交差する二層構造の弾幕を作り出します。", "Pentagram Burst", EnemyPat_Pentagram_Zai },
	{ "DeepSeek76", "ボスが2体居る弾幕", "双星交差「クロスファイア・ロンド」", "左右に2体のボス（青・赤）が同時出現し、互いに逆方向へ動きながら弾幕を交差させる。交差散弾、連結レーザー、双星ロンドの3段階で攻撃する。", "Cathedral Overdrive", EnemyPat_TwoBoss_DeepSeek },
	{ "ChatGPT76", "ボスが2体居る弾幕", "双星「シンクロナイズド・オービット」", "画面上部に2体のボスが左右対称に出現し、互いを中心にするように円運動しながら弾幕を展開します。2体は常に同じタイミングで弾を撃ちますが、片方は時計回り、もう片方は反時計回りに弾を回転させるため、2体の弾幕が中央で交差して巨大な螺旋模様を作ります。", "Cathedral Overdrive", EnemyPat_TwoBoss_ChatGPT },
	{ "Gemini76", "ボスが2体居る弾幕", "共鳴する双極（バイポーラ・レゾナンス）", "青いボスが画面全体に低速のリング弾幕を放ち、途中で弾を一時静止させて格子状の安全地帯（安地）を形成する。その直後に赤いボスがプレイヤーの位置へ向けて高速レーザーを放ち、弾を屈折させながら画面を走破する。プレイヤーは格子状の静止弾のスキマを見極めつつ、直前に隣のマスへ滑り込んでレーザーを避ける、パズル要素の高い連携弾幕。", "Cathedral Overdrive", EnemyPat_TwoBoss_Gemini },
	{ "Grok76", "ボスが2体居る弾幕", "双子の螺旋", "左右に配置した2体のボスが、時計回りと反時計回りの螺旋弾を同時に放って中央で絡み合わせ、その後扇状弾と直線弾を交差させ、円形弾の収縮・拡散を完全同期させ、最後に縦レーザーを左右から寄せて逃げ場を狭める一連の連携弾幕。", "Cathedral Overdrive", EnemyPat_TwoBoss_Grok },
	{ "Claude76", "ボスが2体居る弾幕", "阿吽双獅", "狛犬(阿形・吽形)をモチーフにした双ボス4フェーズパターン。阿形と吽形が画面左右に対称配置され、対峙フェーズでは両者とも中央へ向かう角度を持たない外向きファンのみを撃つため中央通路が常に安全。阿の咆哮フェーズでは阿形が自機狙いで攻め、吽形は白黒交互の石畳カーテンで守る。吽の逆襲フェーズでは役割が交代する。阿吽同時解放フェーズでは両者が半スロットずらして噛み合う同心リングを2波発射しつつ自機狙いを同時に放ち、以後全体をループする。", "Cathedral Overdrive", EnemyPat_TwoBoss_Claude },
	{ "Qwen76", "ボスが2体居る弾幕", "双環交差 ～ Twin Orbit Weave", "2体のボスが左右対称に円運動しながら、互いに逆向きの回転螺旋弾幕を展開して交差する隙間を縫わせる。一定時間ごとにボスが位置を入れ替えて弾幕の流れを反転させ、入れ替え時に出現する結界と自機狙い扇弾への対応を同時に要求するパターン。", "Cathedral Overdrive", EnemyPat_TwoBoss_Qwen },
	{ "Kimi76", "ボスが2体居る弾幕", "双星の共鳴軌道", "画面左右に配置された2体のボスが、フェーズに応じて異なる弾幕を展開する。フェーズ1では左のボスから赤い誘導弾を、右のボスから青い直進弾を射出する。フェーズ2では両ボスが共鳴弾を放ち、赤と青の弾が空中で接触すると、その地点で紫色の拡散弾が8方向に分裂して発生する。フェーズ3では2体が左右に入れ替わり、弾の色も逆転する。プレイヤーは共鳴弾の交差点を予測して避ける必要があり、誘導弾をどこに誘導するかで共鳴地点が変化する。", "Cathedral Overdrive", EnemyPat_TwoBoss_Kimi },
	{ "Zai76", "ボスが2体居る弾幕", "双極交差（ツイン・クロス）・メビウスの帯", "画面左右に配置された2体のボスが逆位相で上下に動きながら、互いの現在位置に向かって赤と青の弾を連射する。真っ直ぐ飛ぶ弾が画面中央で交差した後、進行方向に対して垂直に不規則に揺れる（ノイズゾーンを形成する）仕組みで、動的な隙間が生まれる。", "Cathedral Overdrive", EnemyPat_TwoBoss_Zai },
	{ "DeepSeek77", "ヨーヨーをモチーフにした弾幕", "ヨーヨー弾幕「スピニング・ストリング」", "ヨーヨーの投げつけ・糸の残留・高速回転・巻き戻り・大車輪を弾幕で表現。投げたヨーヨー本体が自機に向かい、通過した軌跡に糸（静止レーザー）を残して移動範囲を制限。停止後は自機狙いの扇状弾と全方位円形弾を放ち、糸を巻き取るように戻りながら左右へ弾をばらまく。戻った後はボスの周囲を大車輪旋回して外側へ螺旋状に弾を放射する。体力が減ると弾速と本数が増加する。", "Centrifugal Breaker", EnemyPat_Yoyo_DeepSeek },
	{ "ChatGPT77", "ヨーヨーをモチーフにした弾幕", "ヨーヨー・リターン", "ボスから放たれた弾が外側へ伸び、一定距離まで進むと反転してボスへ戻り、再び外側へ飛び出す動きを繰り返します。往復距離と発射タイミングをずらすことで、複数のヨーヨーを振り回しているような弾幕を表現します。", "Centrifugal Breaker", EnemyPat_Yoyo_ChatGPT },
	{ "Gemini77", "ヨーヨーをモチーフにした弾幕", "ヨーヨー演舞『アラウンド・スリーパー』", "ボスから自機に向かって巨大な弾（ヨーヨー本体）が超高速で飛んでいき、その通過軌跡に小弾の列（糸）を設置します。到達地点で一瞬停止して周囲に放電弾を散らしたあと、ボスを中心に糸ごと扇状に巨大旋回してプレイヤーの退路を断ちます。最後にヨーヨーがボスへ一気に引き戻されると同時に、糸を構成していた小弾が全方位へ弾けて拡散します。", "Centrifugal Breaker", EnemyPat_Yoyo_Gemini },
	{ "Grok77", "ヨーヨーをモチーフにした弾幕", "ヨーヨー・リターン", "敵からプレイヤー方向へ扇状に弾を発射し、一定距離まで伸びた後に反転して戻ってくる弾幕。戻り時にわずかな揺れを加え、原点付近で消える。", "Centrifugal Breaker", EnemyPat_Yoyo_Grok },
	{ "Claude77", "ヨーヨーをモチーフにした弾幕", "糸繰乱舞", "ヨーヨーをモチーフにした4フェーズ無限ループパターン。投げ下ろしフェーズで本体が紐に沿って揺れながら降下し、スリーピングフェーズでその場で高速自転しながら接線方向へ弾を撒き散らし、アラウンド・ザ・ワールドフェーズで大きな円軌道を振り回されながら火花を残しつつ1周ごとに自機狙い3wayを放ち、巻き戻し・帰還フェーズで加速しながら手元へ戻って全方位バーストと自機狙い5wayで締めくくる。", "Centrifugal Breaker", EnemyPat_Yoyo_Claude },
	{ "Qwen77", "ヨーヨーをモチーフにした弾幕", "ヨーヨー・リターン", "ボスから投げられたヨーヨーがプレイヤーに向かって直進・減速し、最大到達点でその場に停滞しながら周囲の回転弾をばらまいた後、往路とは少し角度を変えてボスのもとへ加速して戻ってくる往復運動の弾幕。本体とボスを繋ぐ糸弾も伸び縮みするため、行きと帰りの二段階の回避が要求される。", "Centrifugal Breaker", EnemyPat_Yoyo_Qwen },
	{ "Kimi77", "ヨーヨーをモチーフにした弾幕", "スリーピング・ヨーヨー", "ボスが巨大な核弾（ヨーヨー本体）を自機に向けて投げ、紐で繋がれた複数の小玉がヨーヨーの動きに連動する。最遠点で核弾が停止し、紐弾が螺旋状に回転しながら内側へ収束する。その後核弾がボスへ戻り、戻り道に紐弾が横一列の壁を形成する。ボス到達時には全弾が一斉に全方位へ拡散し、フィールドを一変させる。投下時は縦の線状弾幕、スリープ時は回転収束、リターン時は手前から迫る壁、バースト時は全方位拡散と、同じ弾群でもフェーズで性質が変化する。", "Centrifugal Breaker", EnemyPat_Yoyo_Kimi },
	{ "Zai77", "ヨーヨーをモチーフにした弾幕", "大車輪", "ヨーヨー本体となる弾が弧を描きながらゆっくり飛んで糸の軌跡を残し、最大到達点で停止して火花を撒いた後、猛スピードで発射元へ巻き取られるように戻る動作を連続発射で網目状にした弾幕。", "Centrifugal Breaker", EnemyPat_Yoyo_Zai },
	{ "DeepSeek78", "世界一楽しい弾幕", "残光曼荼羅 - Phantom Trail -", "自機が移動した軌跡に残光が残り、時間経過で爆発。爆発時に自機狙いの針弾と、他の残光を誘爆させる波紋弾を放出する。避けるほど自分の軌跡が連鎖的に弾幕へ変わる、逆転の発想の弾幕。", "Neon Bullet Frenzy", EnemyPat_TheMostFun_DeepSeek },
	{ "ChatGPT78", "世界一楽しい弾幕", "万華鏡の中で遊ぶ", "シアンの外周リングと白の内周リングが逆方向に回転しながら広がり、弾幕の中に安全な一本道が生まれます。終盤には両方のリングが中央へ巻き込まれて巨大な万華鏡を形成し、直後に中心から一気に炸裂します。", "Neon Bullet Frenzy", EnemyPat_TheMostFun_ChatGPT },
	{ "Gemini78", "世界一楽しい弾幕", "潮汐の輪舞（タイダル・ロンド）", "絶望的な密度の紫色の低速弾幕の中を、自機に向かって飛んでくる青色の高速弾幕を誘導することで、自機の移動軌跡に沿って紫色の弾幕がダイナミックに押し広げられ、美しい安全なトンネルがリアルタイムで形成される流体風干渉弾幕。受動的に隙間を抜けるのではなく、自らの動きで画面全体を駆け巡り道を切り開く全能感と疾走感を味わえる。", "Neon Bullet Frenzy", EnemyPat_TheMostFun_Gemini },
	{ "Grok78", "世界一楽しい弾幕", "虹色の息継ぎ", "大玉の虹色リングが外側へ広がり、その後中心へ収縮して隙間が開閉する。収縮後に小玉へ分裂して外側へ拡散する。複数のリングを時間差で重ねることで、息を吸う・吐くようなリズムでトンネルが連続して生まれ、避けながらダンスしているような快感が得られる。", "Neon Bullet Frenzy", EnemyPat_TheMostFun_Grok },
	{ "Claude78", "世界一楽しい弾幕", "四片乱塔", "テトリスをテーマにした4フェーズパターン。7種のテトリミノが剛体フォーメーションとして回転しながら降下し、盤面下部に積み上がっていく。横一列が埋まるとその列がレーザー状に左右へ飛散し、自機狙いの反撃弾が返礼として放たれる。積み木が天井まで達すると、全ブロックが盤面中心から放射状に崩壊し、自機狙いの弾とともに最初の降下フェーズへ戻ってループする。", "Neon Bullet Frenzy", EnemyPat_TheMostFun_Claude },
	{ "Qwen78", "世界一楽しい弾幕", "呼吸する花冠（ブレス・コロナ）", "6方向に広がる花びらのような弾がゆっくり回転し、その隙間が呼吸するように開閉する弾幕です。プレイヤーは安全地帯と共に踊るように移動し、リズムに合わせて変化する隙間を楽しみながら、自然にかすり抜け（グレイズ）が発生する快感を味わえます。単に避けるだけでなく、弾幕の中で美しく立ち回ることを目指しました。", "Neon Bullet Frenzy", EnemyPat_TheMostFun_Qwen },
	{ "Kimi78", "世界一楽しい弾幕", "共鳴螺旋（Resonance Spiral）", "プレイヤー周囲に24発の衛星弾が正円を描いて出現し、プレイヤーの動きに0.5秒遅れて引きずられながら回転する。プレイヤーが動くと弾の軌道が楕円に歪み、静止すると正円に戻る。一定時間後、弾は螺旋を描いてプレイヤーへ内側に落ちてくる。弾の色はプレイヤーからの距離に応じて青から赤へ変化し、危険度を直感的に示す。プレイヤーは被害者ではなく弾幕と踊る共同演出者となり、自分だけの回避パターンを創作できる。", "Neon Bullet Frenzy", EnemyPat_TheMostFun_Kimi },
	{ "Zai78", "世界一楽しい弾幕", "フラクタル・フォレスト", "画面上に配置された種弾が時間経過で上下左右に伸びる幹弾となり、さらに幹弾は枝分かれして枝弾へと成長していく弾幕です。画面を区切って配置することで必ず避けられる隙間を残しつつ、弾が成長する未来の地形を予測し、自分だけの道を切り開く開拓感を味わえるようにしています。", "Neon Bullet Frenzy", EnemyPat_TheMostFun_Zai },
	{ "DeepSeek79", "リサジュー曲線をモチーフにした弾幕", "リサージュ・ウィーブ", "リサージュ曲線をモチーフに、ボス周囲に配置した弾が回転・伸縮しながら曲線を描き、曲線上の弾から放射弾や自機狙い低速弾を放つ弾幕。", "Lissajous Drive", EnemyPat_Lissajous_DeepSeek },
	{ "ChatGPT79", "リサジュー曲線をモチーフにした弾幕", "追奏するリサジュー", "敵が自機へ向けて複数の弾を一斉に発射し、弾は自機方向へ進みながら横方向へ周期的に蛇行します。3:2の異なる周期を組み合わせたリサジュー状の揺らぎによって、一直線に迫る弾列が∞字や花弁状の軌跡を描きながら自機へ押し寄せます。", "Lissajous Drive", EnemyPat_Lissajous_ChatGPT },
	{ "Gemini79", "リサジュー曲線をモチーフにした弾幕", "位相織機『リサジュー・ウィーバー』", "リサジュー曲線の軌跡に沿って配置した弾の網（メッシュ）を、位相をずらしながら拡大・変形させて迫らせる弾幕。弾が密集する結び目と空洞（安全地帯）が規則的に描かれ、時間の経過とともに滑らかに輪郭を変えていく空洞を見極めて縫うように避ける、幾何学的な美しさとスリルを楽しめる。", "Lissajous Drive", EnemyPat_Lissajous_Gemini },
	{ "Grok79", "リサジュー曲線をモチーフにした弾幕", "交差する無限軌道（Lissajous Weave）", "敵を中心に複数のリサジュー曲線を同時に描く弾を連続生成する。各弾は曲線上を滑りながら半径を徐々に拡大させ、位相差と周波数比の違いで複雑に交差する織り状の弾幕を形成する。", "Lissajous Drive", EnemyPat_Lissajous_Grok },
	{ "Claude79", "リサジュー曲線をモチーフにした弾幕", "位相蔓紋 -Lissajous-", "リサジュー曲線 x=A・sin(aθ+δ), y=B・sin(bθ) をモチーフにした弾幕。曲線上に弾を1発ずつ配置して描き上げ、完成後は全弾がその軌跡上を流れ続けながら節点から自機狙い弾を発射する。さらに位相差δを揺らして曲線を呼吸するように変形させ、周波数比a:bを連続的にモーフィングさせて密度を高めていき、最終形で静止・予告した後に全弾が中心から放射状に飛散して終わる。", "Lissajous Drive", EnemyPat_Lissajous_Claude },
	{ "Qwen79", "リサジュー曲線をモチーフにした弾幕", "リサジュー・ルーム", "3対4の周波数比を持つリサジュー曲線を弾の軌道そのものとして利用した弾幕です。複数の弾の帯が位相をずらしながら降下し、まるで空中で織物を編むように複雑な幾何学模様を形成します。弾は直進するのではなく曲線上を滑るように移動するため、プレイヤーは交差するリボンの隙間や、アーチ状になった弾の下方を縫うようにくぐり抜けて回避します。数学的な規則性による視覚的な美しさと、曲線の流れを読んで安全地帯を見極めるという、予測と反応を組み合わせた新しい回避体験を提供します。", "Lissajous Drive", EnemyPat_Lissajous_Qwen },
	{ "Kimi79", "リサジュー曲線をモチーフにした弾幕", "追跡する位相花", "リサジュー曲線上を周回する親弾を砲台とし、そこから自機方向へ子弾を連射する弾幕。フェーズ1では1対1の楕円軌道上の8砲台が自機を狙い、フェーズ2では2対1の8の字軌道で砲台が回転して発射点を予測困難にし、フェーズ3では3対2の5花弁軌道が高速回転して全方位からの高密度自機狙いを形成する。親弾の軌道交差点では複数砲台が密集して子弾密度が急上昇し、位相回転により安全地帯が常に移動するため、同じ地点に留まると包囲される。", "Lissajous Drive", EnemyPat_Lissajous_Kimi },
	{ "Zai79", "リサジュー曲線をモチーフにした弾幕", "交差結界「リサジューの無限迷路」", "時間経過に伴って位相を変化させることで、3:2のリサジュー曲線が回転・変形していく様子を直進弾で描画します。赤とシアンの2色の小玉を少しずらして発射して交差する網目を形成し、原点付近での弾の密集を防ぐため接線ベクトルの長さを逆算して等間隔に配置することで、美しい幾何学模様と変化し続ける回避隙間を生み出しています。", "Lissajous Drive", EnemyPat_Lissajous_Zai },
	{ "DeepSeek80", "北風と太陽をモチーフにした弾幕", "北風と太陽 ～旅人の外套を脱がせる勝負～", "北風と太陽が自機を旅人に見立てて弾幕で外套を脱がせようとする勝負を描く。北風は高速の青い針弾と渦を描く氷晶弾で力ずくに攻め、太陽は放射状の光弾と日輪リングで包み込む。最終段階では両者が同時に攻撃し、縦横に交差する網目状の弾幕を形成する。", "North Wind Sun", EnemyPat_NorthWindAndSun_DeepSeek },
	{ "ChatGPT80", "北風と太陽をモチーフにした弾幕", "北風と太陽", "前半は青い風弾が左右から激しく吹き付け、画面を横切るように迫ります。後半は太陽を思わせる暖色の弾がゆっくり広がりながら自機へ迫り、最後には北風の弾が外側へ吹き飛ばし、太陽の弾が中央へ引き寄せることで、二つの力がぶつかり合う巨大な渦を作ります。", "North Wind Sun", EnemyPat_NorthWindAndSun_ChatGPT },
	{ "Gemini80", "北風と太陽をモチーフにした弾幕", "旅人の上着を剥ぐ旋風と陽炎", "北風による押し流しと太陽による接近要求を交互に突きつける切り替え型弾幕。北風フェーズでは上からの吹き降ろしと氷の針によって画面下部へ押し込まれ、続く太陽フェーズでは画面下部からせり上がる熱波を避けるため、ボスの懐へ飛び込む立ち回りを強制する。", "North Wind Sun", EnemyPat_NorthWindAndSun_Gemini },
	{ "Grok80", "北風と太陽をモチーフにした弾幕", "北風と太陽の競演", "北風は左右から高速の青系弾を突風のように飛ばしてプレイヤーを押しやり、太陽は中心から低速の黄橙系弾を放射状に広げてじわじわと逃げ場を狭め、一定時間後に小さな二次弾を加えてさらに範囲を拡大する。力ずくの北風と優しく包み込む太陽の対比を弾の性質で表現した周期パターン。", "North Wind Sun", EnemyPat_NorthWindAndSun_Grok },
	{ "Claude80", "北風と太陽をモチーフにした弾幕", "北風太陽争闘", "「北風と太陽」をモチーフにした4フェーズのボスパターン。外周から弾が渦を巻きながら収束し上空に暗雲の輪郭を形作るところから始まり、続いて左右から横殴りの突風弾が波状に襲来する。力任せに攻めるほど安全地帯が狭まっていくことで、北風が強めるほど旅人が身を固くするという寓話の皮肉を表現する。次に太陽の番として、中心から暖色の同心リングがゆったり拡散する優しい弾幕に切り替わり、時間とともに弾数を間引くことで逆に安全地帯が広がっていく。最後に暗雲が点滅して予告したのち、暗雲そのものと新たな放射状の弾幕が中心から一斉に加速しながら飛び散り、太陽の勝利を締めくくる。その後は最初のフェーズへ戻ってループする。", "North Wind Sun", EnemyPat_NorthWindAndSun_Claude },
	{ "Qwen80", "北風と太陽をモチーフにした弾幕", "北風と太陽～旅人の外套を脱がせし者～", "イソップ寓話の対比構造を弾幕の性質とボスの挙動で表現した構成です。第一フェーズでは、速い弾や直線的な攻撃で無理やり外套を剥ぎ取ろうとする北風の激しさを、ボスの素早い往復運動と共に描きます。第二フェーズでは、遅い弾や広がるリングで視界と退路を狭め、自ら外套を脱がざるを得ない状況を作る太陽の穏やかなる圧迫感を、円運動で表現します。最終フェーズでは両者の弾幕が融合し、物語の結末に向けた激しい競い合いを展開します。", "North Wind Sun", EnemyPat_NorthWindAndSun_Qwen },
	{ "Kimi80", "北風と太陽をモチーフにした弾幕", "北風と太陽の賭け", "北風と太陽の寓話を弾幕で表現。北風は画面を横切る風と冷気の針で力ずくに押し、太陽は同心円状の陽光と追従する熱波で誘い込む。最終盤では両者の力が混ざり、回転する渦巻き弾が襲いかかる。弾の色と動きで冷たい風と温かい光の対比を演出する。", "North Wind Sun", EnemyPat_NorthWindAndSun_Kimi },
	{ "Zai80", "北風と太陽をモチーフにした弾幕", "北風と太陽", "前半は高速で飛ぶ直線弾を左右にばら撒く北風パターンで、隙間を見つけてやり過ごす避け方が求められる。後半はプレイヤーをゆっくり追尾する大玉と、画面外から中心に向かって徐々に迫るリング状の弾からなる太陽パターン。熱波に押し潰されないよう自ら動いて道を切り開く必要があり、同じ技の中で避け方の性質をガラッと変える構成。", "North Wind Sun", EnemyPat_NorthWindAndSun_Zai },
	{ "DeepSeek81", "処理落ちをモチーフにした弾幕", "フレームスキップ・バラージュ", "処理落ちをモチーフにした弾幕。弾が滑らかに動かず、カクつきながらワープし、移動前の位置に残像を残す。定期的に画面全体がフリーズし、直後に弾が大きくワープしたり、新しい弾がポップインする。見た目は混雑しているが、当たり判定は最新の弾のみで、残像はフェイク。", "Frame Drop Parade", EnemyPat_Lag_DeepSeek },
	{ "ChatGPT81", "処理落ちをモチーフにした弾幕", "処理落ち", "弾幕が激しくなるにつれて画面全体の動きが徐々に重くなり、弾や敵の動きがほとんど停止します。限界まで処理落ちしたように見せた後、一気に動きが復帰して弾幕が再び激しく動き出す、処理落ちそのものを演出にした弾幕です。", "Frame Drop Parade", EnemyPat_Lag_ChatGPT },
	{ "Gemini81", "処理落ちをモチーフにした弾幕", "クロックダウン・スパイラル", "ゲームの処理負荷が高騰して画面が一時停止したように見せかけ、再開時に弾が一気にワープして押し寄せる時空歪曲型弾幕。渦巻き状に展開される弾幕が途中で完全停止し、進行方向に未来の位置を示す残像が表示された後、処理落ち解消とともに残像の先端へ一瞬でコマ飛びし、弾の色を変えて周囲に拡散射出される。", "Frame Drop Parade", EnemyPat_Lag_Gemini },
	{ "Grok81", "処理落ちをモチーフにした弾幕", "フレームドロップ・カスケード", "弾が普通に飛んでいる最中に突然全体が止まり、停止が解けた瞬間に溜まっていた移動量を一気に適用してワープする。時間経過とともに発生間隔が短くなり、処理落ちが悪化していく様子を表現した弾幕。", "Frame Drop Parade", EnemyPat_Lag_Grok },
	{ "Claude81", "処理落ちをモチーフにした弾幕", "処理落ち再現", "処理落ちという現象そのものを弾幕のモチーフにしたパターン。全ての弾が共有する仮想的な経過時間を歪ませることで、通常速度で密度が高まっていく前半から、見た目上ほとんど停止したようにガクガクと進む疑似処理落ち状態へ移行する。この間も敵は水面下で弾を撒き続け、プレイヤーに油断を誘う。やがて溜め込まれた遅れを一気に解消する反動で、弾群が急加速して襲いかかる早送りフェーズに突入し、最後は通常速度の落ち着いた弾幕で締めて次のサイクルへ戻る。", "Frame Drop Parade", EnemyPat_Lag_Claude },
	{ "Qwen81", "処理落ちをモチーフにした弾幕", "Frame Drop Spiral", "ゲーム全体の動作を重くするのではなく、敵弾の座標更新タイミングだけを意図的に間引いたり停止させたりすることで、処理落ちやフリーズを擬似的に表現するギミックです。フリーズ中は弾が静止しているように見えますが、内部的には移動量が蓄積されており、復旧した瞬間にその差分が一気に適用されることで、弾がワープして襲いかかるような挙動を示します。プレイヤーは現在の弾の位置ではなく、停止解除後に弾が現れる予測座標を読んで回避する必要があります。", "Frame Drop Parade", EnemyPat_Lag_Qwen },
	{ "Kimi81", "処理落ちをモチーフにした弾幕", "フレームドロップ・カスケード", "弾の位置更新を間引くことで、処理落ちしたかのようなカクカクとした動きを演出する。弾は画面端に触れるたびに分裂し、弾数が増えることで画面が重くなっていくような演出を伴う。弾数が一定数を超えると、全弾が一時的に完全停止し、処理落ちのピークであるフリーズ状態を模倣する。その後、全弾の更新間隔が通常に戻り、速度が上昇して一斉にプレイヤーへ襲いかかる。停止中に構築した安全地帯が一変するギャップが、避けの核心となる。", "Frame Drop Parade", EnemyPat_Lag_Kimi },
	{ "Zai81", "処理落ちをモチーフにした弾幕", "演算遅延：ラグ・テレポーション", "ゲームのフレームレートが低下したかのように、弾の移動と完全な停止を繰り返す弾幕です。停止中は弾が残像となり当たり判定も消滅するため、プレイヤーは油断して残像の隙間に入ろうとしますが、その後一瞬で距離をスキップしてワープするため、予測される到達位置を先読みして避ける必要があります。速さや停止間隔の異なる複数の弾を交差させることで、視覚的なごまかしとプレイヤーの錯覚を誘発します。", "Frame Drop Parade", EnemyPat_Lag_Zai },
    { "DeepSeek82", "布団が吹っ飛んだをモチーフにした弾幕", "布団吹雪（ふとんふぶき）", "布団型に並べた弾が風ではためき、吹っ飛ぶと同時に綿のように散る弾幕。通常弾の色と形を組み合わせて布団の面・縁・縫い目・綿を表現する。", "Flying Futon Frenzy", EnemyPat_FutonFlewAway_DeepSeek },
    { "ChatGPT82", "布団が吹っ飛んだをモチーフにした弾幕", "布団が吹っ飛んだ！", "通常弾を大量に組み合わせ、中央に大きな長方形の「布団」を形作るように配置します。布団は画面内をゆっくり漂った後、突然「吹っ飛んで」斜め方向へ高速移動します。その反動で布団を構成していた弾が四方八方へ飛び散り、さらに別の場所から新しい布団が飛んでくる展開を繰り返します。布団が飛び去る瞬間に弾の隙間が生まれるため、その隙間を見極めて避ける弾幕にします。", "Flying Futon Frenzy", EnemyPat_FutonFlewAway_ChatGPT },
    { "Gemini82", "布団が吹っ飛んだをモチーフにした弾幕", "風雲！布団が吹っ飛んだ", "中弾を格子状に並べて四隅に大弾を配した一枚の布団弾幕を作成し、ゆっくりと揺らめきながら下降させます。そこへ画面端から高速の針弾による突風を吹き付け、直撃した瞬間に布団を一気に崩壊させます。布面を構成していた中弾がらせんを描きながら画面全体へ広範囲に吹き飛び、四隅の大弾が遅れて時間差で自機を狙って迫るダイナミックな弾幕パターンです。", "Flying Futon Frenzy", EnemyPat_FutonFlewAway_Gemini },
    { "Grok82", "布団が吹っ飛んだをモチーフにした弾幕", "布団が吹っ飛んだ！！！", "通常弾を横長の格子状に並べて布団の形を作り、しばらく静止させた後、一気に上方向へ高速で吹き飛ばす。外側ほど大きく左右に広がり、一部の弾はゆっくり下へ落ちて端がめくれる様子を表現する。", "Flying Futon Frenzy", EnemyPat_FutonFlewAway_Grok },
    { "Claude82", "布団が吹っ飛んだをモチーフにした弾幕", "布団が吹っ飛んだ", "赤白市松模様の布団を模した弾のグリッドが中心から広がって敷かれ、静かな就寝フェーズを迎える。そこにそよ風が吹き込むとグリッドがさざ波のように揺れ始め、四隅から自機狙いの弾が飛んで突風の予兆を伝える。やがて突風が吹き荒れると、布団は形を保ったまま回転しながら対角線状に加速して吹っ飛び、反対側から現れたもう一枚の布団とすれ違う。吹っ飛び終えた瞬間、布団を構成していた弾がその場から綿埃のように放射状へ飛び散り、追い打ちの自機狙い弾で締めくくる。", "Flying Futon Frenzy", EnemyPat_FutonFlewAway_Claude },
    { "Qwen82", "布団が吹っ飛んだをモチーフにした弾幕", "強風注意報！布団が吹っ飛んだ", "専用の画像を使わず、白とシアン色の小さな円形弾を格子状に隙間なく密集させることで一枚の布団を表現します。発射直後は布団の形を保ったままゆっくりと漂う巨大な壁として機能しますが、一定時間が経過すると突風が吹いたかのように配置が一斉に崩壊します。布団の縁取りを表す弾は外側へ大きく広がり、中身の綿を表す弾は風になびくように波打ちながら画面全体にヒラヒラと舞い散る軌道を描き、言葉通りの布団が吹っ飛ぶ現象を弾幕の挙動と視覚効果で再現します。", "Flying Futon Frenzy", EnemyPat_FutonFlewAway_Qwen },
    { "Kimi82", "布団が吹っ飛んだをモチーフにした弾幕", "朝の覚醒―布団吹飛び", "敵が巨大な布団型の弾幕を自機に向かって被せてくる。布団の縁は高密度で中心は薄く、安全地帯の選択を迫る。一定時間後、布団が一斉に画面外へ吹っ飛び、その衝撃で大量の羽毛弾が自機周囲に発生する。羽毛弾は減速しながらゆらゆらと漂い、フィールドを継続的に脅かす。布団の閉塞感から解放される爽快感と、残る羽毛による緊張感の対比を演出する。", "Flying Futon Frenzy", EnemyPat_FutonFlewAway_Kimi },
    { "Zai82", "布団が吹っ飛んだをモチーフにした弾幕", "真冬の突風「奪われた寝床」", "中玉の弾を長方形に敷き詰めて布団を表現した塊が、擬似的な立体回転をしながらバサバサと羽ばたくように揺れながら画面上方へ飛んでいくメインの動き。それに伴い、布団からは遅い小さな弾で綿ぼこりがこぼれ落ち、布団が通った軌跡上を速いレーザー状の弾が突風となって遅れて走ることで、布団が吹っ飛ぶ一連の動きを表現した弾幕。", "Flying Futon Frenzy", EnemyPat_FutonFlewAway_Zai },
    { "DeepSeek83", "虹をモチーフにした弾幕", "虹環「スペクトラル・ハレーション」", "虹をモチーフに、七色の弾が同心円状のリングを形成し、色ごとに回転速度や半径を変えて波打つ。一定時間後に接線方向へ虹色のレーザーを放ち、さらに全弾が中心へ収束した後、八方向へ放射状に弾を撒く。", "Prismatic Sky", EnemyPat_Rainbow_DeepSeek },
    { "ChatGPT83", "虹をモチーフにした弾幕", "虹色七連弾", "七色の弾が順番に放たれ、弧を描きながら巨大な虹を形成する。虹がプレイヤーを包み込むように変化した後、中央へ収束して一気に外側へ弾ける、虹の完成と崩壊を表現した弾幕。", "Prismatic Sky", EnemyPat_Rainbow_ChatGPT },
    { "Gemini83", "虹をモチーフにした弾幕", "スペクトル「プリズム・スペクトルアーチ」", "ボスを中心として虹色の弾幕が弧を描いて広がり、画面中央で一時静止して虹を形成します。その後、可視光線の波長に応じた固有の挙動へと変化します。赤や橙などの長波長は自機へ直線的に突き進み、黄や緑の中波長は大きくS字にうねりながら降下、水色や紫などの短波長はゆっくり停滞しながら周囲へ小さな弾を拡散させます。色ごとの運動特性を攻略に活かす鮮やかな弾幕です。", "Prismatic Sky", EnemyPat_Rainbow_Gemini },
    { "Grok83", "虹をモチーフにした弾幕", "虹のアーチ弾幕", "敵の位置を基準に虹色の弾が大きな弧を描いて並び、色の順番に時間差をつけてプレイヤー方向へ波のように押し寄せる。頂点付近からは小さな二次反射弾も飛来する。", "Prismatic Sky", EnemyPat_Rainbow_Grok },
    { "Claude83", "虹をモチーフにした弾幕", "七色架橋", "雨上がりの空に虹がかかる様子をモチーフにした弾幕。斜めに降り注ぐ雨がやがて弱まり、中心から七色の弧が頂点から左右へ弧を描くように伸びて形成される。完成した虹は各色ごとに外向きの弾を周期的に放ち続け、しばらくすると一回り外側に色の並びを反転させた副虹が現れる。主虹と副虹は互いに逆向きにゆったりと揺れ動き、その振幅が最大になる瞬間に合わせて自機狙いの弾を同期して放つ。最後に予告ののち、虹を形作っていた弾がすべてその場から放射状に加速しながら飛び散り(外側の色ほど緩やかに、内側の色ほど鋭く)、同時に本体から自機狙いの弾をまとめて放って締めくくる。", "Prismatic Sky", EnemyPat_Rainbow_Claude },
    { "Qwen83", "虹をモチーフにした弾幕", "七彩分光アーク", "光がプリズムを通ると色ごとに屈折率が異なる物理現象を弾幕の軌道に応用したものです。弾の色によって移動速度と曲がる角度を変化させ、緩やかな弧を描く色と急激に曲がる色が重なり合うことで、画面を横断する美しい虹のアーチを形成します。発射方向に応じて回転方向を調整することで敵を頂点とした左右対称の虹を表現し、視覚的な美しさと軌道法則の予測による回避の快感を両立させます。", "Prismatic Sky", EnemyPat_Rainbow_Qwen },
    { "Kimi83", "虹をモチーフにした弾幕", "七色円弧陣 プリズムアーチ", "ボスが七色の弾を扇状に発射し、色ごとに異なる曲率で円弧を描いて虹の橋を形成する。弾は一定時間滞留した後、画面中央で白色の閃光弾が全方向に展開し、虹の帯と白い光の網が重なる。さらに滞留していた各虹弾が自機狙いの細弾を放ちながら下へ落下し、多層的な避けごたえを演出する。", "Prismatic Sky", EnemyPat_Rainbow_Kimi },
    { "Zai83", "虹をモチーフにした弾幕", "交差する七色のアーチ", "敵を中心に七色の弾で虹のアーチを順番に描画します。完成したアーチは隣り合う色同士で互い違いに回転し始め、絶えず変化する隙間を縫う回避を迫る弾幕です。", "Prismatic Sky", EnemyPat_Rainbow_Zai },
    { "DeepSeek84", "スピログラフをモチーフにした弾幕", "スピログラフ・ギア・バースト", "固定した外歯車の内側を、内歯車が転がりながらスピログラフ曲線を描き、曲線上に置いた弾を放射状に発射する弾幕。放射が終わるたびに内歯車の半径を変化させ、異なる花びら模様を次々と生成する。", "Bullet Rain Gate", EnemyPat_Spirograph_DeepSeek },
    { "ChatGPT84", "スピログラフをモチーフにした弾幕", "歯車が描くスピログラフ", "通常の敵弾を組み合わせて内側と外側の歯車を表現し、噛み合うように回転させることで、歯車の動きに沿って菱形弾がスピログラフ状の幾何学模様を描きます。", "Bullet Rain Gate", EnemyPat_Spirograph_ChatGPT },
    { "Gemini84", "スピログラフをモチーフにした弾幕", "幾何軌跡「スピロ・トロコイド」", "敵弾を組み合わせて構成した固定の大歯車と、その内側を転がる小歯車を表現し、ペンの軌跡となる弾幕で幾何学模様を描き出します。模様が完成すると歯車を形成していた弾は吹き飛んで退場し、残された幾何学模様の弾幕が一斉に加速・回転しながら広がって攻撃へと変化します。", "Bullet Rain Gate", EnemyPat_Spirograph_Gemini },
    { "Grok84", "スピログラフをモチーフにした弾幕", "二重歯車の軌跡", "外側に円形に並べた通常弾をゆっくり回転させて大きな歯車を表現し、その内側を公転しながら自転する発射点から弾を放射する。放射された弾に外側の回転の影響を少し加えることで、スピログラフのような曲線軌跡を描く。", "Bullet Rain Gate", EnemyPat_Spirograph_Grok },
    { "Claude84", "スピログラフをモチーフにした弾幕", "渦転花紋", "専用の歯車素材がないため、通常弾を円周上に並べて半径を交互に変化させることで歯車のギザギザを表現する。外側の固定リングギアと内側のピニオンを弾で描き上げたのち、ピニオンが内側を転がりながら公転と自転を行い、そのペン先の軌跡としてハイポトロコイド曲線を弾で描き足していく。歯先や噛み合い部分からは自機狙いの弾や煌めきを継続的に放ち、転動が止まると描き終えた曲線が中心から緩やかに拡大していく。最後に予告ののち、歯車と曲線のすべての弾が中心を基準に放射状へ加速しながら一斉に飛び散り、自機狙いの弾を放って締めくくる。", "Bullet Rain Gate", EnemyPat_Spirograph_Claude },
    { "Qwen84", "スピログラフをモチーフにした弾幕", "スピログラフ・ギア：回転歯車の軌跡", "画面中央に固定された外側の歯車と、その内側を公転および自転する内側の歯車を、通常の弾幕素材の組み合わせで表現します。内側の歯車が回転する際に、その歯の位置に速度ゼロの弾を生成し続けることで、数学的に美しいスピログラフ特有の花びら状の曲線軌跡を描き出します。さらに、内歯車の歯の先から外向きに小弾を発射することで、静的な幾何学模様と動的な弾幕が融合した華やかな攻撃パターンを構築します。", "Bullet Rain Gate", EnemyPat_Spirograph_Qwen },
    { "Kimi84", "スピログラフをモチーフにした弾幕", "機巧星華 － Mechanical Spirograph", "外歯車と内歯車を通常の敵弾の輪で表現する弾幕。外歯車は大きな円周上に弾を配置し、弾のサイズを交互に変えることで歯の凹凸を演出する。内歯車は外歯車の内側を公転しつつ自転し、同様に弾サイズの交互配置で小さな歯車を表現する。内歯車の周上にある複数の描画点から弾を発射させ、スピログラフ曲線を描きながら広がる軌道美を形成する。フェーズ進行により回転速度の変化、描画点数の増加、外歯車の回転方向反転、外歯車の縮小などが発生し、単純な幾何学美からカオス的な高密度弾幕へと変化する。内歯車の中心から散る火花エフェクトで歯車の噛み合いを演出する。", "Bullet Rain Gate", EnemyPat_Spirograph_Kimi },
    { "Zai84", "スピログラフをモチーフにした弾幕", "ハイポトロコイド・ギアワークス", "通常の弾を円状に配置し、一部を大きくすることで外側と内側の歯車を表現します。内側の歯車は外側の歯車の内壁をすべるように公転しながら逆方向に自転します。内側の歯車の歯の先端から接線方向に弾を発射し続け、その軌跡がスピログラフの美しい曲線を描きます。一定時間経過後、歯車の形を維持していた弾自体が外側へ放射状に飛び散り、画面がリセットされるように次の波が訪れます。", "Bullet Rain Gate", EnemyPat_Spirograph_Zai },
	{ "tmp", "ここに弾幕の短い説明が入る", "ここに弾幕タイトルが入る", "ここにAIによる弾幕の長ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーい説明が入る", "Torpedo_Hymn", EnemyPat_Tmp },
};